# -*- coding: utf-8 -*-
"""Roster del Capítulo 1: 48 especies de balance.json + 6 secretos = 54 entradas de Catdex."""

AURA = {  # tríada summon.colors de cats-metadata.json (deepsea/masquerade ya corregidos al arte real)
    "alien_galaxy_cat": ["#7dff6f", "#59f5ff", "#ffe978"],
    "mecha_neon_cat": ["#3dfcff", "#ff3fd8", "#7ea0ff"],
    "lantern_spirit_cat": ["#ffe28c", "#a7d8ff", "#b4a2ff"],
    "prism_crystal_cat": ["#7fe0ff", "#ff89ff", "#ffe78d"],
    "mushroom_druid_cat": ["#ffcf68", "#ffd54d", "#c9ff83"],
    "molten_ember_cat": ["#ff5c2a", "#ffb22a", "#ffef7a"],
    "jelly_aquatic_cat": ["#a3f7ff", "#8ac6ff", "#ffb8ff"],
    "neon_glitch_cat": ["#43e8ff", "#ff49ef", "#ffb143"],
    "steampunk_clockwork_cat": ["#eac06b", "#8ee4ff", "#e49b51"],
    "regal_cosmic_cat": ["#ffd974", "#8cc8ff", "#c48cff"],
    "kintsugi_tea_spirit_cat": ["#d4a64b", "#3157b7", "#f5e6be"],
    "iridescent_origami_cat": ["#8d6bff", "#56d8ff", "#ffa748"],
    "stormcloud_elemental_cat": ["#d8ecff", "#64b5ff", "#498fff"],
    "candy_alchemist_cat": ["#ff82d7", "#60e4ff", "#ffe06f"],
    "masquerade_phantom_cat": ["#8c2bff", "#1f0f36", "#d296ff"],
    "fossilstone_guardian_cat": ["#44d9e6", "#d1b37b", "#8ef7ff"],
    "deepsea_sprite_cat": ["#7cb0ff", "#d6d8ff", "#5de0ff"],
    "cyber_bloom_cat": ["#6cff78", "#ff8dde", "#d4ff72"],
    "storybook_ink_cat": ["#211818", "#c7a77d", "#5e4a43"],
    "mochi_bell_cat": ["#d4a549", "#4f6db8", "#f2e2b4"],
    "nori_lunar_cat": ["#b8d5ff", "#6ea7ff", "#24386f"],
    "sakura_whisper_cat": ["#ffb6d0", "#ff8fb8", "#ffdce8"],
    "sol_sunbeam_cat": ["#ffb431", "#ffe17a", "#ff7a18"],
    "selene_moonlit_cat": ["#9ec8ff", "#dff1ff", "#6e86e7"],
    "menta_botanical_cat": ["#79a45d", "#dcefc9", "#537f47"],
    "canelo_cozy_cat": ["#b87b4b", "#efcfb2", "#7e5135"],
    "nube_dream_cat": ["#9fbfff", "#f1f7ff", "#d4e4ff"],
    "arce_autumn_cat": ["#d56b2e", "#f0b45c", "#b64924"],
    "margarita_daisy_cat": ["#e7c34d", "#90b757", "#fff7d6"],
    "sonata_prima_cat": ["#d4a54a", "#2d2b42", "#fff1c7"],
    "lumen_lens_cat": ["#5f88d7", "#f5e9cf", "#9c6f47"],
    "bytewhisker_cat": ["#4d63c8", "#f0b24c", "#dbe4ff"],
}

RECARGA = {"common": 0, "rare": 1, "epic": 1, "legendary": 2, "mythic": 2}


def T(hue=0, sat=1.0, bright=1.0, overlay=None, alpha=0.0, decal=None, scale=1.0, aura=None):
    return {"hue": hue, "sat": sat, "bright": bright, "overlay": overlay, "overlayAlpha": alpha,
            "decal": decal, "scale": scale, "aura": aura}


def shot(name, arch, el, dmg, radius=1.5, proj=1, spread=0, bounces=0, pierce=0, status=None, turns=0,
         grav=1.0, speed=1.0, special=None, cry=None):
    return {"name": name, "cry": cry, "archetype": arch, "element": el, "dmg": dmg, "radius": radius,
            "projectiles": proj, "spreadDeg": spread, "bounces": bounces, "pierce": pierce,
            "status": status, "statusTurns": turns, "gravityMul": grav, "speedMul": speed, "special": special}


def ult(name, effect, dmg=None, cost=100, uses=None, charge=0, cap=0.35):
    return {"name": name, "effect": effect, "dmg": dmg, "meterCost": cost, "usesPerBattle": uses,
            "chargeTurns": charge, "structureCap": cap}


def cat(id, name, epithet, slug, tint, el, rarity, role, trait, form, shot_, ult_, passive, star3, star5,
        obtain, hint, lore, limitation=None, worker=None, primordial=False, secret=False, recarga=None,
        econ_note=None, gold_mod=None, gambit_mod=None, sets=None):
    aura = (tint or {}).get("aura") if tint else None
    return {
        "id": id, "name": name, "epithet": epithet, "art": {"slug": slug, "tint": tint, "aura": aura or AURA[slug]},
        "elements": el, "rarity": rarity, "primordial": primordial, "secret": secret,
        "role": role, "worker": worker, "trait": trait,
        "battleForm": {"name": form[0], "cry": form[1]},
        "economy": {"goldBasePerS": "balance:rarities.gold_base_per_s." + rarity,
                    "powerBase": "balance:rarities.power_base." + rarity,
                    "foodMult": "balance:rarities.food_mult." + rarity,
                    "goldMod": gold_mod, "note": econ_note, "gambitMod": gambit_mod},
        "combat": {"hpBase": "roles." + role + ".hp", "recarga": RECARGA[rarity] if recarga is None else recarga,
                   "shot": shot_, "ultimate": ult_, "limitation": limitation, "passive": passive,
                   "star3": star3, "star5": star5},
        "obtain": obtain, "hint": hint, "lore": lore,
    }


CATS = [
    # ------------------------------------------------------------------ COMUNES (14)
    cat("c_canelo", "Canelo", "el Impaciente", "canelo_cozy_cat", None, ["fire"], "common", "artillero", "impaciente",
        ("CANELO — INFERNAL FORM", "HAIRBALL IGNITION!!"),
        shot("Hairball Ignition", "bola_rebote", "fire", 60, 1.5, bounces=1, status="ardiendo", turns=2,
             special="Bola de pelo incendiada. La bufanda se vuelve capa en llamas en la Battle Form.", cry="HAIRBALL IGNITION!!"),
        ult("HAIRBALL BARRAGE! (毛玉乱射)", "Tres bolas de pelo en abanico (spread 12°), cada una rebota 1 vez. Ardiendo 2.", dmg=55),
        "Calorcito: +10% daño a celdas de madera.",
        "★3: la bola deja un charco ardiente 1 turno donde explota.",
        "★5: +1 rebote (Hellball junior).",
        {"source": "start", "how": "Inicial. Duerme en una caja de cartón al empezar."},
        None, "Nació para dormir en una caja. Lo despertaste para incendiar barcos. Ahora es tu problema.",
        sets=["set_brasas"]),
    cat("c_chispa", "Chispa", "la Sonrisa Peligrosa", "sol_sunbeam_cat",
        T(hue=-12, sat=1.25, overlay="#ff6a1a", alpha=0.18, decal="brasas", scale=0.92, aura=["#ff6a1a", "#ffc94a", "#ff2e2e"]),
        ["fire"], "common", "artillero", "travieso",
        ("CHISPA — SPARK MODE", "SUNNY SIDE UP!"),
        shot("Chispazo", "bola_rebote", "fire", 55, 1.2, status="ardiendo", turns=1, grav=0.8, speed=1.2,
             special="Rápida y tensa: buena para tiros directos."),
        ult("SUNNY SIDE UP! (目玉焼き)", "Lluvia de 5 chispas sobre una zona 4x2 del barco enemigo. Ardiendo 1.", dmg=35),
        "Iniciativa: si es el primer gato en disparar en la batalla, +15% daño.",
        "★3: sus chispas que caen al agua rebotan una vez hacia el casco.",
        "★5: Ardiendo que aplica también Revela la celda.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🔥 (Común)."},
        "Dicen que nace de una chispa con demasiada confianza.", "Si la ves sonreír, agáchate.",
        worker="banker", sets=["set_brasas", "set_oficio"]),
    cat("c_gelatino", "Gelatino", "el Blandito", "jelly_aquatic_cat", None, ["water"], "common", "asediador", "gloton",
        ("GELATINO — ABYSS JELLY FORM", "TIDAL COMPRESSION!"),
        shot("Torpedo de Gelatina", "torpedo", "water", 55, 1.2, status="mojado", turns=2,
             special="Brecha bajo la línea de flotación."),
        ult("TIDAL COMPRESSION! (潮圧)", "Presión desde abajo: daña toda la fila de la línea de flotación enemiga (x0.8) y abre 2 brechas.", dmg=50),
        "Rebote blandito: el primer golpe directo que recibe por batalla hace 50% menos.",
        "★3: sus brechas inundan +25% más rápido.",
        "★5: al morir suelta un charco que Moja 3x3 de tu barco (apaga incendios).",
        {"source": "start", "how": "Inicial."},
        None, "Tiembla cuando tiene miedo. Tiembla cuando está feliz. Tiembla.",
        worker="farmer", sets=["set_marea", "set_oficio"]),
    cat("c_burbujas", "Burbujas", "la Efervescente", "jelly_aquatic_cat",
        T(hue=40, sat=1.15, bright=1.1, overlay="#a3f7ff", alpha=0.2, decal="burbujas", scale=0.92, aura=["#a3f7ff", "#ffb8ff", "#ffffff"]),
        ["water"], "common", "soporte", "presumido",
        ("BURBUJAS — FIZZ FORM", "BUBBLE PARTY!"),
        shot("Burbujazo", "bola_rebote", "water", 40, 1.5, status="mojado", turns=2, grav=0.7, speed=0.8,
             special="Lento; al impactar Moja un área 3x3."),
        ult("BUBBLE PARTY! (泡祭り)", "Burbuja-escudo sobre tu módulo más dañado (anula 1 impacto) y Moja todo el barco enemigo.", dmg=0),
        "Espuma: tus celdas Ardiendo adyacentes a su camarote se apagan al inicio de tu turno.",
        "★3: la burbuja-escudo también cura 10% al módulo.",
        "★5: Burbujazo deja Mojado 3 turnos.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 💧 (Común)."},
        "Aparece donde alguien se baña. Nadie sabe por qué.", "Es 70% gas. El otro 30% es actitud.",
        sets=["set_marea"]),
    cat("c_brote", "Brote", "la Margarita Terca", "margarita_daisy_cat", None, ["nature"], "common", "asediador", "curioso",
        ("BROTE — PETAL ARMOR FORM", "FRESH BLOOM!"),
        shot("Semilla de Margarita", "semilla", "nature", 45, 1.0, status="enraizado", turns=2,
             special="DoT de la enredadera: 15 por turno."),
        ult("FRESH BLOOM! (開花)", "Limpia todos los estados de tu barco y cura 15% a todos tus módulos.", dmg=0),
        "Rocío: tus módulos Ardiendo adyacentes a su camarote pierden 1 turno de fuego.",
        "★3: la semilla aplica también Revelado.",
        "★5: su ultimate además deja tus módulos inmunes a Ardiendo 1 turno.",
        {"source": "start", "how": "Inicial."},
        None, "Se ve tierna con su margarita en la oreja. Pelea como chile.",
        worker="farmer", sets=["set_raiz"]),
    cat("c_musgo", "Musgo", "el que Nunca se Mueve", "menta_botanical_cat", None,
        ["nature"], "common", "tanque", "perezoso",
        ("MUSGO — MOSS WALL FORM", "MOSS WALL!"),
        shot("Bola de Musgo", "semilla", "nature", 50, 1.2, status="enraizado", turns=1),
        ult("MOSS WALL! (苔壁)", "Hace crecer 4 celdas de muro-enredadera (60 de vida c/u) delante de un módulo propio elegido.", dmg=0),
        "Raíces: su camarote tiene +30% de vida.",
        "★3: el muro de musgo regenera 10% por turno.",
        "★5: los gatos en camarotes adyacentes reciben −15% daño.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🌿 (Común)."},
        "Crece donde nadie barre.", "Huele a menta fresca. Lleva tres días en la misma posición. Dice que es una estrategia.",
        worker="builder", sets=["set_raiz", "set_oficio"]),
    cat("c_terron", "Terrón", "de Azúcar", "kintsugi_tea_spirit_cat", None, ["earth"], "common", "soporte", "leal",
        ("TERRÓN — GOLDEN SEAM FORM", "KINTSUGI!"),
        shot("Taza Voladora", "roca", "earth", 60, 1.0, pierce=1, grav=1.6, special="Una taza de porcelana que pega como ladrillo."),
        ult("KINTSUGI! (金継ぎ)", "Repara 25% de un módulo propio y lo deja 'sellado en oro': +20% vida máxima hasta el final de la batalla.", dmg=0),
        "Grietas doradas: cada módulo que repares recibe −20% del siguiente golpe.",
        "★3: Kintsugi repara también las celdas destruidas adyacentes (1 por uso).",
        "★5: Taza Voladora perfora +1 capa.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🪨 (Común). Requiere Tierra descubierta."},
        "Lo que se rompe y se repara con oro vale más. Dicen.", "Porcelana que se rompió mil veces y siempre volvió más bonita. Le dicen Terrón porque endulza el té… y te avienta la taza.",
        worker="builder", sets=["set_piedra"]),
    cat("c_guijarro", "Guijarro", "la Cría de Piedra", "fossilstone_guardian_cat",
        T(hue=10, sat=0.6, bright=1.1, overlay="#d1b37b", alpha=0.15, decal=None, scale=0.88, aura=["#d1b37b", "#8ef7ff", "#6b5c3f"]),
        ["earth"], "common", "demoledor", "bravucon",
        ("GUIJARRO — AMMONITE CUB FORM", "AMMONITE QUAKE!"),
        shot("Amonita", "roca", "earth", 70, 1.0, pierce=2, grav=1.6),
        ult("AMMONITE QUAKE! (地震)", "Onda sísmica: 25% de su daño a todas las celdas enemigas con 1 solo apoyo (provoca colapsos).", dmg=60),
        "Pesado: no lo empujan las ráfagas ni el viento.",
        "★3: Amonita deja la celda de impacto 'agrietada' (+20% daño recibido 2 turnos).",
        "★5: su ultimate además desactiva 1 turno el motor enemigo.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🪨 (Común)."},
        "Las crías de Gea se esconden en los acantilados.", "Pequeño pero denso. Muy denso. No lo cargues.",
        sets=["set_piedra"]),
    cat("c_voltio", "Voltio", "el Cable Pelado", "mecha_neon_cat",
        T(hue=50, sat=1.1, bright=1.1, overlay="#ffe14a", alpha=0.18, decal="rayos", scale=0.9, aura=["#ffe14a", "#00e5ff", "#ffffff"]),
        ["storm"], "common", "francotirador", "curioso",
        ("VOLTIO — LIVE WIRE FORM", "ZAP ZAP ZAP!"),
        shot("Rayito", "rayo", "storm", 50, 0.8, status="cargado", turns=1, grav=0.2, speed=1.6,
             special="Conducción con Mojado; Sobrecarga contra hierro."),
        ult("ZAP ZAP ZAP! (ビリビリ)", "Tres rayos rápidos a tres módulos marcados (clic en cada uno).", dmg=45),
        "Puntería: vista previa de trayectoria +30%.",
        "★3: Rayito Revela al gato del módulo impactado.",
        "★5: Conducción iniciada por él aturde 2 turnos.",
        {"source": "resonance", "how": "Resonancia con al menos un padre ⚡ (Común). Requiere Tormenta descubierta."},
        "Siempre anda cerca de los charcos. Mala idea.", "El primo chiquito de Raijin. Le encanta lamer enchufes.",
        worker="voyager", sets=["set_tormenta", "set_oficio"]),
    cat("c_nimbo", "Nimbo", "la Siesta con Viento", "nube_dream_cat", None, ["storm"], "common", "controlador", "dormilon",
        ("NIMBO — CUMULUS QUEEN FORM", "CUMULUS NAP!"),
        shot("Ventolera", "rafaga", "storm", 35, 1.0, status="corriente", turns=1, grav=0.0,
             special="Empuja; Ventisca sobre Mojado (Congelado)."),
        ult("CUMULUS NAP! (積雲の昼寝)", "Nube de sueño 4x3: los cañones enemigos dentro no disparan el siguiente turno y sus gatos quedan Aturdidos.", dmg=0),
        "Siesta salvadora: una vez por batalla, si recibe un golpe letal, se duerme y queda con 1 de vida.",
        "★3: la Corriente que deja dura 2 turnos.",
        "★5: puede saltarse 1 turno enemigo completo una vez por batalla (como ultimate gratis).",
        {"source": "resonance", "how": "Resonancia con al menos un padre ⚡ (Común)."},
        "Aparece cuando el cielo tiene sueño.", "Pelea dormida. Gana dormida. No la despiertes.",
        sets=["set_tormenta"]),
    cat("c_linterna", "Linterna Espíritu", "la que Alumbra lo Feo", "lantern_spirit_cat", None, ["magic"], "common", "controlador", "chismoso",
        ("LINTERNA — SOUL BEACON FORM", "WILL-O'-WISP PARADE!"),
        shot("Fuego Fatuo", "runa", "magic", 45, 1.0, status="maldito", turns=1,
             special="Busca solo el módulo más débil del barco enemigo; además lo deja Revelado."),
        ult("WILL-O'-WISP PARADE! (鬼火行列)", "Tres fuegos fatuos teledirigidos a los 3 módulos más débiles: Revelados 3 turnos.", dmg=40),
        "Faro: mientras viva, ignoras la Niebla y ves la vida de todos los gatos enemigos.",
        "★3: Fuego Fatuo también Revela el camarote vecino.",
        "★5: los módulos Revelados reciben +30% (en vez de +20%).",
        {"source": "resonance", "how": "Resonancia con al menos un padre ✨ (Común). Requiere Magia descubierta."},
        "Brilla donde se esconden los errores.", "Ilumina el siguiente paso. Nunca el camino completo. Le gusta el drama.",
        sets=["set_arcana"]),
    cat("c_caramelo", "Caramelo Alquimista", "Dulcera", "candy_alchemist_cat", None, ["magic"], "common", "asediador", "presumido",
        ("DULCERA — GRAND TRANSMUTER FORM", "SUGAR RUSH TRANSMUTATION!"),
        shot("Frasco Caramelo", "bola_rebote", "magic", 50, 1.3, status="maldito", turns=1,
             special="Convierte madera/hierro del impacto en caramelo quebradizo (Maldito)."),
        ult("SUGAR RUSH TRANSMUTATION! (錬金)", "Un módulo enemigo se vuelve caramelo: el siguiente golpe físico lo destruye completo (núcleo: solo x2).", dmg=0),
        "Sobredosis: Maldito que aplica dura +1 turno.",
        "★3: el frasco salpica Maldito a 1 módulo vecino.",
        "★5: Transmutación funciona en 2 módulos.",
        {"source": "resonance", "how": "Resonancia con al menos un padre ✨ (Común)."},
        "Huele a algodón de azúcar y a química ilegal.", "Transforma sesiones pesadas en caramelo. Y barcos también.",
        worker="banker", sets=["set_arcana"]),
    cat("c_cometin", "Cometín", "el Visitante Chiquito", "alien_galaxy_cat",
        T(hue=150, sat=1.0, bright=1.1, overlay="#59f5ff", alpha=0.2, decal="estrellas", scale=0.9, aura=["#59f5ff", "#ffffff", "#8a5cff"]),
        ["cosmic"], "common", "artillero", "curioso",
        ("COMETÍN — LITTLE VISITOR FORM", "COLLAPSING ORBIT!"),
        shot("Mini Planeta", "orbe_gravitatorio", "cosmic", 55, 1.3, status="ingravido", turns=1, speed=0.7),
        ult("COLLAPSING ORBIT! (崩壊軌道)", "Pozo de gravedad 1 turno: atrae escombros y proyectiles cercanos y aplasta el módulo (x1.8).", dmg=55),
        "Turista: +10% daño en su primera batalla contra cada zona nueva.",
        "★3: el pozo de la ultimate dura 2 turnos.",
        "★5: Mini Planeta orbita 1 vez el núcleo antes de impactar (+15% hacia el núcleo).",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🌌 (Común). Requiere Cósmico descubierto."},
        "Llegó en un cometa del tamaño de una pelota.", "Nadie sabe de qué planeta es. Él tampoco.",
        worker="voyager", sets=["set_estrellas"]),
    cat("c_lunita", "Lunita", "la del Lado Oscuro", "nori_lunar_cat",
        T(hue=20, sat=0.9, bright=1.25, overlay="#b8d5ff", alpha=0.22, decal="lunas", scale=0.9, aura=["#b8d5ff", "#6ea7ff", "#ffffff"]),
        ["cosmic"], "common", "francotirador", "miedoso",
        ("LUNITA — DARK SIDE FORM", "SILENT ECLIPSE!"),
        shot("Rayo Lunar", "orbe_gravitatorio", "cosmic", 55, 1.0, status="ingravido", turns=1, grav=0.5,
             special="Invisible para el rival hasta impactar (la IA no lo puede esquivar ni anticipar)."),
        ult("SILENT ECLIPSE! (月蝕)", "Oscurece el campo 2 turnos: el rival pierde la vista previa de trayectoria.", dmg=0),
        "Nocturna: +15% daño en batallas de noche o con niebla.",
        "★3: el eclipse también baja 20% el daño enemigo.",
        "★5: Rayo Lunar perfora 1 capa.",
        {"source": "resonance", "how": "Resonancia con al menos un padre 🌌 (Común)."},
        "Solo sale cuando nadie la ve.", "Del lado oscuro de la luna. Literal. Y emocional.",
        sets=["set_estrellas"]),

    # ------------------------------------------------------------------ RAROS (16)
    cat("r_neblino", "Neblino", "el Vaporcito", "nube_dream_cat",
        T(hue=-30, sat=0.7, bright=1.0, overlay="#ffb0a0", alpha=0.18, decal="vapor", aura=["#ffffff", "#ff9f9f", "#a3f7ff"]),
        ["fire", "water"], "rare", "controlador", "dormilon",
        ("NEBLINO — STEAM CURTAIN FORM", "STEAM CURTAIN!"),
        shot("Bocanada de Vapor", "bola_rebote", "fire", 55, 1.5, status="mojado", turns=1,
             special="Siempre crea Vapor 3x3 en el impacto (aplica Mojado+Ardiendo a la vez)."),
        ult("STEAM CURTAIN! (蒸気の幕)", "Cortina de vapor delante de tu barco 2 turnos: los tiros enemigos que la cruzan pierden 30% de daño y la vista previa.", dmg=0),
        "Nublado: los gatos enemigos que le apuntan tienen vista previa −30%.",
        "★3: el Vapor que crea dura 3 turnos.",
        "★5: la cortina también Moja tu barco (apaga incendios).",
        {"source": "resonance", "how": "Resonancia cuya unión de elementos incluya 🔥 y 💧 (p. ej. Canelo + Gelatino)."},
        "Sale cuando el fuego y el agua se ponen de acuerdo.", "\"Okay, salió vapor…\" — tú, la primera vez.",
        sets=["set_vapor"]),
    cat("r_pimenton", "Pimentón", "el Vendaval de Otoño", "arce_autumn_cat", None, ["fire", "nature"], "rare", "asediador", "travieso",
        ("PIMENTÓN — CRIMSON GALE FORM", "AUTUMN INFERNO!"),
        shot("Hojarasca Picante", "bola_rebote", "fire", 30, 0.8, proj=3, spread=8, status="marcado", turns=2,
             special="3 hojas ardientes; cada módulo tocado queda Marcado."),
        ult("AUTUMN INFERNO! (紅葉旋風)", "Tornado de hojas en llamas que recorre una fila completa de la cubierta enemiga: Ardiendo + Marcado.", dmg=40),
        "Marcador: el siguiente gato que golpee un módulo Marcado hace crítico garantizado.",
        "★3: +1 hoja.",
        "★5: las hojas que caen al agua vuelven a subir una vez.",
        {"source": "resonance", "how": "Resonancia cuya unión de elementos incluya 🔥 y 🌿. Primera Resonancia del tutorial (Canelo + Brote): resultado garantizado en 90 s (balance.timer_rules.tutorial_first_resonance)."},
        "Huele a otoño y a parrillada.", "Soltar un intento también es aprender. Soltar un tornado de hojas en llamas, más.",
        worker="banker"),
    cat("r_nenufar", "Nenúfar", "la Flor que Flota", "sakura_whisper_cat", None, ["water", "nature"], "rare", "soporte", "presumido",
        ("NENÚFAR — PETAL OATH FORM", "PETAL OATH!"),
        shot("Me Quiere, No Me Quiere", "runa", "nature", 25, 0.8, proj=5, spread=20,
             special="5 pétalos (PRNG con semilla): cada uno cura 8% a un módulo propio O hace 25 de daño crítico a uno enemigo. La UI muestra cada pétalo."),
        ult("PETAL OATH! (花の誓い)", "Cura 20% a todos tus módulos y limpia sus estados.", dmg=0),
        "Suerte de flor: +5% de crítico a todo el equipo.",
        "★3: los pétalos de cura también dan +10 de medidor al gato del módulo.",
        "★5: 6 pétalos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 💧 y 🌿."},
        "Florece donde el agua está quieta.", "Me quiere, no me quiere, me quiere… te hunde.",
        worker="farmer"),
    cat("r_magmito", "Magmito", "el Hijo de la Fragua", "molten_ember_cat",
        T(hue=15, sat=1.0, bright=1.15, overlay="#ff9a3a", alpha=0.2, decal="grietas_lava", scale=0.88, aura=["#ff9a3a", "#ffef7a", "#4e0000"]),
        ["fire", "earth"], "rare", "demoledor", "piromano",
        ("MAGMITO — LITTLE FORGE FORM", "LAVA BOMB!"),
        shot("Roca Fundida", "roca", "fire", 75, 1.2, pierce=1, status="ardiendo", turns=2, grav=1.4),
        ult("LAVA BOMB! (溶岩弾)", "Bola de magma que deja un charco ardiente 3 turnos en 3 celdas en línea.", dmg=70),
        "Caliente: sus impactos contra celdas Congeladas hacen x2 (deshielo violento).",
        "★3: el charco se propaga también por hierro.",
        "★5: +1 capa de perforación.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y 🪨."},
        "Cuentan que Ignis tuvo hijos. Este salió con mal genio.", "Una piedra que nunca se enfrió. Tampoco piensa hacerlo.",
        sets=None),
    cat("r_fanguito", "Fanguito", "el Charco con Patas", "kintsugi_tea_spirit_cat",
        T(hue=-20, sat=0.6, bright=0.8, overlay="#6b4a2b", alpha=0.3, decal="lodo", aura=["#6b4a2b", "#a3f7ff", "#d4a64b"]),
        ["water", "earth"], "rare", "tanque", "gloton",
        ("FANGUITO — MUDSLIDE FORM", "MUDSLIDE!"),
        shot("Bola de Lodo", "roca", "water", 55, 1.2, status="mojado", turns=2, grav=1.3, speed=0.85,
             special="Además deja Embarrado: si toca un cañón, pierde su próximo disparo."),
        ult("MUDSLIDE! (泥流)", "Avalancha de lodo: el compartimento impactado se inunda 25% al instante y abre brecha.", dmg=55),
        "Barro: −20% de daño de fuego recibido.",
        "★3: Embarrado dura 2 turnos.",
        "★5: su camarote es inmune a Ardiendo.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 💧 y 🪨."},
        "Aparece después de la lluvia en los acantilados.", "Era una taza de té. Se cayó al lodo. Le gustó.",
        sets=None),
    cat("r_raizvieja", "Raíz Vieja", "la Abuela del Bosque", "mushroom_druid_cat",
        T(hue=25, sat=0.7, bright=0.85, overlay="#857b1b", alpha=0.2, decal="raices", scale=0.92, aura=["#c9ff83", "#a57454", "#4d4b0c"]),
        ["nature", "earth"], "rare", "invocador", "perezoso",
        ("RAÍZ VIEJA — ELDER ROOT FORM", "ROOT QUAKE!"),
        shot("Hongo Mina", "semilla", "nature", 40, 1.0, status="enraizado", turns=2,
             special="Planta un hongo: al final de cada turno revienta (40 en área 1) y se propaga a 1 módulo adyacente (máx. 3 hongos)."),
        ult("ROOT QUAKE! (根地震)", "Raíces levantan la cubierta: 50 de daño a 2 filas y Enraizado 2 turnos.", dmg=50),
        "Paciencia: sus hongos hacen +10% por cada turno que sobreviven.",
        "★3: máx. 4 hongos.",
        "★5: los hongos no se queman con fuego normal.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🌿 y 🪨."},
        "La raíz más vieja del bosque costero ronca de noche.", "Silvana la dejó cuidando el bosque. No ha soltado el bastón en 300 años.",
        worker="builder"),
    cat("r_plasmin", "Plasmín", "el Enchufe Caliente", "mecha_neon_cat",
        T(hue=-140, sat=1.2, bright=1.0, overlay="#ff2e88", alpha=0.2, decal="plasma", aura=["#ff2e88", "#ff6a1a", "#00e5ff"]),
        ["fire", "storm"], "rare", "francotirador", "bravucon",
        ("PLASMÍN — OVERHEAT FORM", "PLASMA OVERDRIVE!"),
        shot("Bala de Plasma", "rayo", "fire", 85, 0.8, status="ardiendo", turns=1, grav=0.2, speed=1.6,
             special="Aplica Ardiendo y Cargado. +25% contra hierro."),
        ult("PLASMA OVERDRIVE! (プラズマ)", "Rayo que atraviesa TODO el barco enemigo en línea recta (perforación infinita) a x1.0.", dmg=70),
        "Sobrecalentado: +25% daño contra hierro.",
        "★3: la ultimate aplica Ardiendo a cada celda que atraviesa.",
        "★5: el KO por cañón de cristal le deja 1 de vida una vez por batalla.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y ⚡."},
        "Nace cuando un rayo cae en una fogata.", "Brillante, rápido y frágil. Como tu ex.",
        limitation={"id": "glass", "text": "CAÑÓN DE CRISTAL: si su camarote recibe CUALQUIER golpe, queda KO (cae al agua). Camarote con brillo rojo en la UI."}),
    cat("r_marejada", "Marejada", "la Marea de Plata", "selene_moonlit_cat", None, ["water", "storm"], "rare", "tanque", "leal",
        ("MAREJADA — SILVER TIDE FORM", "SILVER TIDE!"),
        shot("Ola Lunar", "torpedo", "water", 55, 1.3, status="mojado", turns=2,
             special="Al llegar al casco sube como ola: Moja 3x2 y empuja a los gatos expuestos 1 celda."),
        ult("SILVER TIDE! (銀の潮)", "Alza la marea bajo el barco enemigo (vista previa enemiga −50% 2 turnos) y pone un escudo de cristal (anula 1 impacto) en tu módulo más dañado.", dmg=0),
        "Luna llena: tus módulos con escudo reflejan 15% del daño que reciben.",
        "★3: Ola Lunar aplica Corriente.",
        "★5: el escudo de cristal anula 2 impactos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 💧 y ⚡."},
        "La marea sube cuando la luna se enoja.", "Guarda los permisos nocturnos del mar. Y los cobra.",
        worker="voyager"),
    cat("r_cyberbloom", "Cyber Bloom", "el Jardinero Protocolo", "cyber_bloom_cat", None, ["nature", "storm"], "rare", "soporte", "curioso",
        ("CYBER BLOOM — OVERGROWTH PROTOCOL", "OVERGROWTH PROTOCOL!"),
        shot("Semilla Dron", "semilla", "nature", 70, 0.8,
             special="Se clava y germina: revienta al final del SIGUIENTE turno enemigo desde dentro (ignora cobertura y escudos)."),
        ult("OVERGROWTH PROTOCOL! (過成長)", "Repara 15% a todos tus módulos y planta 3 semillas dron en módulos enemigos.", dmg=50),
        "Mantenimiento: al inicio de tu turno repara 5% al módulo propio más dañado.",
        "★3: la semilla dron Revela el módulo mientras germina.",
        "★5: repara 8% en vez de 5%.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🌿 y ⚡."},
        "Florece cuando detecta una secuencia rota.", "Mitad jardín, mitad algoritmo. 100% chismosa con los bugs.",
        worker="farmer"),
    cat("r_iman", "Imán", "Tictoque el Maquinista", "steampunk_clockwork_cat", None, ["earth", "storm"], "rare", "controlador", "leal",
        ("IMÁN — CLOCKWORK FORM", "STEAM OVERLOAD!"),
        shot("Bala Magnética", "roca", "earth", 60, 1.2, pierce=1, grav=1.4,
             special="Al impactar atrae escombros en radio 2 (cada escombro +10 daño). Sobrecarga contra hierro."),
        ult("STEAM OVERLOAD! (蒸気過負荷)", "Cañón de vapor que empuja 2 módulos enemigos 1 celda (puede romper sus soportes y provocar colapso).", dmg=40),
        "Cuerda: cada 3 turnos, el siguiente aliado que dispare no gasta su recarga.",
        "★3: Cuerda cada 2 turnos.",
        "★5: la ultimate empuja 3 módulos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🪨 y ⚡."},
        "Hace tic-tac. Si deja de hacerlo, corre.", "Regula el tiempo con engranajes. Y los barcos enemigos con imanes.",
        worker="banker"),
    cat("r_arcanito", "Arcanito", "el Farolito Rabioso", "lantern_spirit_cat",
        T(hue=180, sat=1.2, bright=1.0, overlay="#ff6a1a", alpha=0.22, decal="runas", aura=["#ff6a1a", "#ff2e88", "#ffe28c"]),
        ["fire", "magic"], "rare", "asediador", "piromano",
        ("ARCANITO — ARCANE BONFIRE FORM", "ARCANE BONFIRE!"),
        shot("Fuego Arcano", "runa", "fire", 55, 1.0, status="ardiendo", turns=2, special="Aplica Ardiendo y Maldito."),
        ult("ARCANE BONFIRE! (秘火)", "Cuatro runas de fuego que buscan cuatro módulos distintos.", dmg=40),
        "Llama eterna: su fuego no se apaga con agua (el Vapor no lo extingue).",
        "★3: +1 runa en la ultimate.",
        "★5: Fuego Arcano Amplifica estados presentes.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y ✨."},
        "Una linterna que se enojó.", "Su fuego no lo apaga ni el mar. Lo intentaron.",
        sets=None),
    cat("r_mareaenc", "Marea Encantada", "la Sirena de la Biblioteca", "deepsea_sprite_cat",
        T(hue=60, sat=1.1, bright=1.05, overlay="#d296ff", alpha=0.22, decal="runas", aura=["#d296ff", "#7cb0ff", "#ffffff"]),
        ["water", "magic"], "rare", "controlador", "chismoso",
        ("MAREA ENCANTADA — UNDERTOW FORM", "ENCHANTED UNDERTOW!"),
        shot("Ola Hechizada", "torpedo", "water", 50, 1.2, status="mojado", turns=2,
             special="Torpedo que además gira hacia el módulo marcado (homing) y aplica Maldito."),
        ult("ENCHANTED UNDERTOW! (魔潮)", "Remolino: arrastra a un gato enemigo Expuesto al agua (pierde 2 turnos) o, si no hay, inunda un compartimento 40%.", dmg=0),
        "Amplifica: el Mojado que aplica dura el doble.",
        "★3: Ola Hechizada perfora 1 mamparo.",
        "★5: el remolino arrastra hasta 2 gatos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 💧 y ✨."},
        "Canta en la biblioteca hundida. Prohibido hacer ruido.", "Lee mareas como si fueran libros. Los subraya con brechas.",
        sets=["set_vapor"]),
    cat("r_origami", "Origami Iridiscente", "Ori de Mil Pliegues", "iridescent_origami_cat", None, ["nature", "magic"], "rare", "artillero", "travieso",
        ("ORI — CRANE STORM FORM", "THOUSAND CRANES!"),
        shot("Mil Grullas", "runa", "nature", 22, 0.6, proj=4, spread=14,
             special="4 grullas; x2 contra lona (velas, mástiles) y cuerdas; ignoran escudos de energía."),
        ult("THOUSAND CRANES! (千羽鶴)", "Enjambre de 12 grullas teledirigidas a velas, mástiles y camarotes.", dmg=20),
        "Plegable: −25% de daño recibido de explosiones de área.",
        "★3: +1 grulla.",
        "★5: las grullas que fallan regresan una vez.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🌿 y ✨."},
        "Pliega lo complicado hasta volverlo filoso.", "Mil pliegues. Mil cortes. Cero arrugas.",
        worker="builder"),
    cat("r_runachispa", "Runa Chispa", "Bytewhisker (root)", "bytewhisker_cat", None, ["storm", "magic"], "rare", "controlador", "chismoso",
        ("BYTEWHISKER — KERNEL MODE", "KERNEL PANIC: SUDO RM!"),
        shot("Kernel Panic", "rayo", "storm", 40, 0.8, status="sellado", turns=2, grav=0.2, speed=1.5,
             special="'Crashea' el módulo: desactivado 2 turnos (Sobrecarga)."),
        ult("KERNEL PANIC: SUDO RM! (強制終了)", "Apaga 2 módulos 2 turnos; si alguno se destruye mientras está crasheado, el error rebota a un vecino (60 de daño).", dmg=0),
        "Debug: ves el siguiente objetivo de la IA (icono de mira sobre el módulo o gato que van a atacar).",
        "★3: Kernel Panic también baja 20 de medidor al gato del módulo.",
        "★5: la ultimate apaga 3 módulos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya ⚡ y ✨."},
        "Compila pistas. Detecta bugs. Ejecuta permisos que no debería tener.", "Root. Sudo. Michi.",
        sets=None),
    cat("r_solar", "Solar", "el Mediodía Eterno", "sol_sunbeam_cat", None, ["fire", "cosmic"], "rare", "francotirador", "impaciente",
        ("SOL — ETERNAL NOON FORM", "HIGH NOON!"),
        shot("Rayo de Mediodía", "rayo", "fire", 65, 0.8, status="ardiendo", turns=1, grav=0.3, speed=1.5,
             special="Funde metal: +25% contra hierro."),
        ult("HIGH NOON! (正午)", "Haz solar que barre una columna completa del barco enemigo de arriba abajo; el siguiente aliado no gasta recarga.", dmg=55),
        "Amanecer: en el turno 1 todos tus gatos ganan +20 de medidor.",
        "★3: el haz aplica Ardiendo a toda la columna.",
        "★5: Amanecer da +30.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y 🌌."},
        "Corre más rápido que la pereza de la tarde.", "Energía contagiosa. Insolación también.",
        sets=None),
    cat("r_astral", "Astral", "la Viajera del Tarot", "alien_galaxy_cat",
        T(hue=90, sat=1.1, bright=1.0, overlay="#c48cff", alpha=0.22, decal="estrellas", aura=["#c48cff", "#ffd974", "#59f5ff"]),
        ["magic", "cosmic"], "rare", "artillero", "presumido",
        ("ASTRAL — ARCANA FORM", "ASTRAL PROJECTION!"),
        shot("Carta Astral", "orbe_gravitatorio", "magic", 30, 1.0, proj=1,
             special="Acción en vuelo: se divide en 3 cartas (30 c/u) con Maldito + Ingrávido."),
        ult("ASTRAL PROJECTION! (星幽体)", "Copia la última ultimate aliada usada en esta batalla al 60% (no copia 'una vez por batalla' de Míticos).", dmg=0),
        "Destino: 10% (PRNG) de que su disparo sea 'carta mayor' (x2).",
        "★3: 'carta mayor' 15%.",
        "★5: copia la ultimate al 75%.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya ✨ y 🌌."},
        "Lee tu futuro. Sale que te hunden. Te sigue cayendo bien.", "Viaja entre estrellas con un mazo de cartas y cero plan.",
        worker="voyager"),

    # ------------------------------------------------------------------ ÉPICOS (9) — poderosos con limitación
    cat("e_vaporronin", "Vapor Ronin", "el que Vuelve", "sakura_whisper_cat",
        T(hue=0, sat=0.85, bright=1.05, overlay="#dff1ff", alpha=0.12, decal="vapor", aura=["#ffffff", "#ffb6d0", "#a3f7ff"]),
        ["fire", "water"], "epic", "francotirador", "bravucon",
        ("VAPOR RONIN — HANAMI STEAM FORM", "MIL PÉTALOS: STEAM SLASH!"),
        shot("Iaido de Vapor", "rayo", "water", 60, 0.8, status="vapor", turns=1, grav=0.0, speed=2.0,
             special="Corte horizontal de alcance medio (12 celdas). Racha: +15% por cada turno seguido que atacó (máx. x1.6)."),
        ult("MIL PÉTALOS: STEAM SLASH! (千本桜)", "Tormenta de pétalos-cuchilla de vapor: 6 cortes de 35 a la fila del camarote enemigo más dañado.", dmg=35),
        "Racha samurái: +15% acumulable por turno consecutivo atacando.",
        "★3: revive con 75% en vez de 60%.",
        "★5: al revivir hace un Iaido gratis.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y 💧, ambos padres Nv15+. Mutación estrella: Conductividad."},
        "Dicen que un ronin que muere en la niebla vuelve como vapor.", "Murió una vez. Le dio flojera quedarse muerto.",
        limitation={"id": "secondLife", "text": "SEGUNDA VIDA (Revenant): al caer KO revive con 60% de vida, pero tarda 2 turnos en volver (vapor sin cuerpo, no actúa ni recibe daño). En la isla produce −30% de oro."},
        gold_mod=0.7, econ_note="−30% oro (CHARLA: Revenant). No simulado en sim.py.", sets=["set_vapor", "set_rotos"]),
    cat("e_infernal", "Canelo Infernal", "el Pirómano", "canelo_cozy_cat",
        T(hue=-10, sat=1.4, bright=0.75, overlay="#4e0000", alpha=0.35, decal="grietas_lava", scale=1.05, aura=["#ff2e2e", "#ff6a1a", "#4e0000"]),
        ["fire", "earth"], "epic", "demoledor", "piromano",
        ("CANELO — INFERNAL FORM", "HELLBALL!!!"),
        shot("Hellball", "bola_rebote", "fire", 70, 1.5, bounces=2, status="ardiendo", turns=2,
             special="Impacta: ¡BOOM! Rebota: ¡BOOM! Si entra por una abertura (celda vacía interior) explota x2: ¡BOOOOOM!"),
        ult("HELLBALL!!! (地獄玉)", "Tres explosiones en cadena que perforan hacia el interior (cada rebote +1 capa).", dmg=70),
        "Pirómano: su Ardiendo dura +1 turno y se propaga también por hierro.",
        "★3: tercer rebote.",
        "★5: cada abertura nueva que abre le da +10 de medidor.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y 🪨, ambos padres Nv15+. Tip: Canelo + un gato de Tierra."},
        "Canelo tiene un lado oscuro. Literal: le salen grietas de lava.", "El mismo gato que dormía en una caja. Ahora parte barcos en tres.",
        limitation={"id": "unstable", "text": "SOBRECALENTADO: cada 3 disparos (no ultimates) pierde su siguiente turno enfriándose. Contador de 3 llamitas en su retrato."}),
    cat("e_golem", "Gólem Musgoso", "la Montaña que Respira", "fossilstone_guardian_cat",
        T(hue=70, sat=0.9, bright=0.9, overlay="#4f8f4a", alpha=0.28, decal="musgo", scale=1.08, aura=["#4f8f4a", "#c9ff83", "#44d9e6"]),
        ["nature", "earth"], "epic", "tanque", "leal",
        ("GÓLEM — LIVING FORTRESS FORM", "LIVING FORTRESS!"),
        shot("Puño Musgoso", "roca", "earth", 90, 1.2, pierce=3, status="enraizado", turns=1, grav=1.8),
        ult("LIVING FORTRESS! (生ける要塞)", "Crea un muro de 6 celdas de piedra-musgo (120 de vida c/u) en tu barco donde elijas.", dmg=0),
        "Guardián: los camarotes adyacentes al suyo reciben −30% daño.",
        "★3: el muro regenera 10% por turno.",
        "★5: alcance +20%.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🌿 y 🪨, ambos padres Nv15+."},
        "Una montaña se quedó dormida en el bosque y le creció un gato.", "Respira cada diez minutos. Es suficiente.",
        limitation={"id": "slow", "text": "PESADO: su disparo solo alcanza el 60% de la potencia máxima (corto alcance) y ocupa 2 espacios de tripulación."},
        worker="builder"),
    cat("e_rencor", "Rencor", "el Gato Vengativo", "arce_autumn_cat",
        T(hue=-25, sat=1.3, bright=0.6, overlay="#c8102e", alpha=0.3, decal="rayos", aura=["#c8102e", "#ffd400", "#0d110f"]),
        ["fire", "storm"], "epic", "demoledor", "rencoroso",
        ("RENCOR — BERSERK FORM", "WRATH OF THE NINE LIVES!"),
        shot("Zarpazo Eléctrico", "rayo", "storm", 70, 1.0, status="cargado", turns=1, grav=0.3,
             special="Daño x Rabia. Sin aliados caídos dispara a x0.7."),
        ult("WRATH OF THE NINE LIVES! (九生の怒り)", "En Berserk: 4 zarpazos a 4 módulos distintos. Fuera de Berserk: 2 zarpazos.", dmg=60),
        "Rencor: la Rabia nunca baja durante la batalla.",
        "★3: Berserk pierde 5% de vida por turno (en vez de 10%).",
        "★5: Rabia inicial x1.2 aunque nadie haya caído.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🔥 y ⚡, ambos padres Nv15+."},
        "Nace del enojo de un gato al que le movieron el plato.", "Cuando un aliado cae, siente la necesidad de destruir la mitad del barco. Y lo hace.",
        limitation={"id": "berserk", "text": "VENGANZA: Rabia x1.5 / x2 / x5 por 1.er, 2.º y 3.er aliado KO. Si queda solo: BERSERK (2 acciones por turno, pierde 10% de vida por turno). Tienes que dejar que maten a tu equipo para llegar ahí."},
        sets=["set_rotos"]),
    cat("e_bastion", "Bastión", "la Refracción Absoluta", "prism_crystal_cat", None, ["earth", "magic"], "epic", "tanque", "presumido",
        ("BASTIÓN — ABSOLUTE REFRACTION FORM", "ABSOLUTE REFRACTION!"),
        shot("Refracción", "rayo", "magic", 60, 0.8, grav=0.2,
             special="Láser que se divide en 3 al cruzar cualquier celda de cristal. Daño x(1 + 0.25 por escudo perdido)."),
        ult("ABSOLUTE REFRACTION! (絶対屈折)", "Espejo 1 turno: el próximo disparo enemigo vuelve contra su barco a x1.5.", dmg=0),
        "Prisma: cuando se le rompe un escudo lanza 3 esquirlas automáticas (20 c/u).",
        "★3: empieza con 4 escudos (y −25% más de precisión por el cuarto).",
        "★5: cada escudo roto le da +15 de medidor.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🪨 y ✨, ambos padres Nv15+."},
        "Hecha del reflejo de mil soluciones correctas.", "Casi imposible de matar. Casi imposible de apuntar con ella.",
        limitation={"id": "shields", "text": "3 ESCUDOS: empieza con 3 escudos (cada uno anula un impacto completo, multi-impactos y magia los rompen rápido). Cada escudo activo reduce su vista previa 25% y la hace temblar."},
        sets=["set_rotos"]),
    cat("e_galaxia", "Galaxia", "la Medusa Sideral", "jelly_aquatic_cat",
        T(hue=70, sat=1.2, bright=0.7, overlay="#204a7a", alpha=0.35, decal="estrellas", scale=1.05, aura=["#8a5cff", "#00e5ff", "#204a7a"]),
        ["water", "cosmic"], "epic", "controlador", "dormilon",
        ("GALAXIA — SIDEREAL JELLY FORM", "GALACTIC UNDERTOW!"),
        shot("Marea de Estrellas", "torpedo", "cosmic", 70, 1.3, status="ingravido", turns=1, speed=0.6,
             special="Torpedo gravitatorio que se curva hacia el núcleo enemigo; aplica Mojado e Ingrávido."),
        ult("GALACTIC UNDERTOW! (銀河逆潮)", "Invierte la gravedad del barco enemigo 1 turno: celdas sueltas y escombros 'caen' hacia arriba y luego se desploman (Lluvia de escombros).", dmg=0),
        "Nebulosa: los gatos enemigos Mojados reciben +20% de daño cósmico.",
        "★3: velocidad del torpedo x0.8 (menos fácil de desviar).",
        "★5: la ultimate dura 2 turnos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 💧 y 🌌, ambos padres Nv15+."},
        "Una medusa que se tragó una galaxia. O al revés.", "Flota. Brilla. Hunde.",
        limitation={"id": "slow_projectile", "text": "LENTA: su proyectil va a x0.6; el viento y la Corriente la desvían el doble."},
        worker="banker"),
    cat("e_meteoro", "Meteoro", "la Lluvia Real", "regal_cosmic_cat",
        T(hue=-150, sat=1.2, bright=0.95, overlay="#ff6a1a", alpha=0.25, decal="brasas", aura=["#ff6a1a", "#ffd974", "#8a5cff"]),
        ["earth", "cosmic"], "epic", "demoledor", "perezoso",
        ("METEORO — ROYAL SHOWER FORM", "ROYAL METEOR SHOWER!"),
        shot("Meteorito Real", "objetivo", "earth", 110, 1.5, pierce=2,
             special="No tiene trayectoria: eliges una celda y cae en vertical desde el cielo. Necesita 1 turno de carga."),
        ult("ROYAL METEOR SHOWER! (流星雨)", "5 meteoros (x0.6) repartidos sobre todo el barco enemigo. Una vez por batalla.", dmg=66, uses=1),
        "Escombros: los trozos que caen por su impacto hacen daño de caída x2.",
        "★3: la carga no se pierde con el primer golpe a su camarote.",
        "★5: 6 meteoros en la ultimate.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🪨 y 🌌, ambos padres Nv15+. Sus orbes salen del evento Estrella Fugaz."},
        "Cae del cielo cuando alguien pide un deseo mal.", "La realeza también cae. Encima de ti.",
        limitation={"id": "charge", "text": "CARGA: necesita 1 turno de carga visible para el rival ('METEOR CHARGING 1/1'). Si su camarote recibe daño mientras carga, pierde la carga."}),
    cat("e_supernova", "Supernova", "la de Una Sola Bala", "sol_sunbeam_cat",
        T(hue=170, sat=0.9, bright=1.2, overlay="#8cc8ff", alpha=0.3, decal="estrellas", aura=["#ffffff", "#8cc8ff", "#c48cff"]),
        ["storm", "cosmic"], "epic", "demoledor", "impaciente",
        ("SUPERNOVA — STARFALL FORM", "STARFALL!!!"),
        shot("Destello", "rayo", "storm", 40, 0.8, grav=0.2, special="Disparo normal flojito: fiable pero meh."),
        ult("STARFALL!!! (星墜)", "Eliges CUALQUIER punto del barco enemigo: cae una estrella que atraviesa 3 pisos. Daño monstruoso (tope 40% de la estructura).", dmg=300, uses=1, cap=0.40),
        "Supermasiva: su medidor empieza lleno (Starfall listo desde el turno 1).",
        "★3: Starfall Revela todo el barco al caer.",
        "★5: Starfall deja un pozo de gravedad 2 turnos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya ⚡ y 🌌, ambos padres Nv15+."},
        "Una estrella que explotó y decidió ser gato.", "Tiene UNA bala. Si pega, borra media nave.",
        limitation={"id": "oneShot", "text": "UNA BALA: Starfall solo se puede usar UNA vez por batalla y necesita la Sala de Invocación viva. Contra-juego: destruir la sala antes. Icono '1' que se apaga."},
        sets=["set_rotos"]),
    cat("e_nebulosa", "Nebulosa", "Astro Nori, el Visitante", "alien_galaxy_cat", None, ["nature", "cosmic"], "epic", "asediador", "curioso",
        ("ASTRO NORI — SUPERNOVA BLOOM FORM", "COLLAPSING NEBULA!"),
        shot("Semilla Nebular", "semilla", "cosmic", 60, 1.2, status="enraizado", turns=2,
             special="Orbita 1 vez el barco enemigo y luego se planta: Enraizado + Ingrávido."),
        ult("COLLAPSING NEBULA! (星雲崩壊)", "Pozo gravitatorio que atrae escombros + enredadera cósmica que ata 3 módulos (Enraizado 2).", dmg=50),
        "Clorofila estelar: sus enredaderas no se queman.",
        "★3: la semilla orbita y se planta en el módulo de mayor valor.",
        "★5: el pozo también desvía proyectiles enemigos.",
        {"source": "resonance", "how": "Resonancia cuya unión incluya 🌿 y 🌌, ambos padres Nv15+."},
        "Nació cuando una constelación olvidada cayó sobre una libreta abierta.", "Antenas de cristal, orejas con galaxias, cero sentido de la orientación.",
        limitation={"id": "delayed", "text": "LAG ESPACIAL: su disparo impacta al FINAL del siguiente turno enemigo (retardado); el rival ve dónde va a caer."},
        worker="farmer"),

    # ------------------------------------------------------------------ PRIMORDIALES (Legendarios, 7)
    cat("l_ignis", "Ignis", "la Primera Llama", "molten_ember_cat", None, ["fire"], "legendary", "demoledor", "piromano",
        ("IGNIS — FORGE HEART FORM", "FIRST FLAME: FORGE ERUPTION!"),
        shot("Erupción de Fragua", "bola_rebote", "fire", 95, 2.0, status="ardiendo", turns=3, grav=1.2,
             special="Cae como meteoro de lava (tiro bombeado); los charcos se propagan por la madera."),
        ult("FIRST FLAME: FORGE ERUPTION! (始原の炎)", "Erupción de 3 columnas de lava; todo lo de madera en radio 3 arde.", dmg=90),
        "Origen del Fuego: todos tus gatos 🔥 hacen +10% de daño.",
        "★3: los charcos duran +1 turno.",
        "★5: Ignition ya no le cuesta vida si el disparo destruye un módulo.",
        {"source": "resonance", "how": "Resonancia de dos padres que COMPARTAN 🔥, ambos Nv20+ (bucket Legendario). También puede salir en '???'."},
        "La primera llama nunca se apagó: solo se fue a dormir en algún gato de fuego.", "Nació en la fragua donde se templan los intentos fallidos. Su fuego no castiga: enseña. Y quema.",
        limitation={"id": "selfdamage", "text": "IGNITION: cada disparo normal le cuesta 5% de su vida."}, primordial=True, sets=["set_brasas", "set_primordiales"]),
    cat("l_abisa", "Abisa", "Madre Marea", "deepsea_sprite_cat", None, ["water"], "legendary", "francotirador", "chismoso",
        ("ABISA — ABYSSAL LURE FORM", "ABYSSAL LURE!"),
        shot("Luz Abisal", "torpedo", "water", 85, 1.2, status="mojado", turns=2,
             special="La antena hipnotiza (el gato objetivo pierde precisión 2 turnos) y la dentellada de presión abre brecha DOBLE."),
        ult("ABYSSAL LURE! (深淵の灯)", "Todos los proyectiles enemigos del próximo turno se desvían al agua; inunda el compartimento enemigo más grande 50%.", dmg=0),
        "Origen del Agua: tus gatos 💧 +10% daño; las brechas inundan +25% más rápido.",
        "★3: la hipnosis dura 3 turnos.",
        "★5: Luz Abisal atraviesa 1 mamparo.",
        {"source": "resonance", "how": "Resonancia de dos padres que compartan 💧, ambos Nv20+."},
        "Hay una luz en el fondo del mar. No la sigas. O sí.", "Creepy-cute certificado. Madre de todas las mareas.",
        limitation={"id": "taunt", "text": "CEBO: su luz atrae el 50% de los disparos enemigos hacia su camarote (la IA prioriza su camarote)."}, primordial=True, sets=["set_marea", "set_primordiales"]),
    cat("l_silvana", "Silvana", "Raíz Primera", "mushroom_druid_cat", None, ["nature"], "legendary", "invocador", "perezoso",
        ("SILVANA — DEEP FOREST DRUID FORM", "PRIMAL FOREST!"),
        shot("Bosque de Esporas", "semilla", "nature", 35, 1.0, proj=2, spread=10, status="enraizado", turns=2,
             special="Siembra 2 hongos que revientan al final de cada turno (35) y se propagan."),
        ult("PRIMAL FOREST! (原始の森)", "Cubre el barco enemigo de micelio: TODAS sus celdas Enraizadas 2 turnos (cañones enraizados no disparan).", dmg=0),
        "Origen de la Naturaleza: tus gatos 🌿 +10%; tus enredaderas curan 3% a tus módulos adyacentes.",
        "★3: 3 hongos por disparo.",
        "★5: sus hongos sobreviven al fuego una vez.",
        {"source": "resonance", "how": "Resonancia de dos padres que compartan 🌿, ambos Nv20+."},
        "La primera raíz conecta todos los bosques. Escucha.", "Crece donde las ideas se conectan bajo la superficie.",
        limitation={"id": "persistent", "text": "PERSISTENTE: sus hongos no hacen nada el turno en que se plantan y el fuego enemigo los destruye."}, primordial=True, sets=["set_raiz", "set_primordiales"]),
    cat("l_gea", "Gea", "Corazón de Piedra", "fossilstone_guardian_cat", None, ["earth"], "legendary", "tanque", "leal",
        ("GEA — AMMONITE COLOSSUS FORM", "HEART OF STONE!"),
        shot("Sismo Ammonite", "roca", "earth", 80, 1.0, pierce=2, grav=1.6,
             special="Además: onda sísmica por el agua que hace 20 a todas las celdas enemigas con ≤1 apoyo (colapsos)."),
        ult("HEART OF STONE! (石の心)", "2 turnos: tus módulos no pueden ser destruidos (quedan en 1 de vida mínimo).", dmg=0),
        "Origen de la Tierra: tus gatos 🪨 +10%; tu quilla tiene +50% de vida.",
        "★3: la onda sísmica hace 30.",
        "★5: Heart of Stone dura 3 turnos.",
        {"source": "boss:1", "how": "Jefe 1 (Capitán Bigotes Rotos): era el 'fósil vivo' de su bodega. Duplicados: Resonancia de dos padres que compartan 🪨, Nv20+."},
        None, "Relik, el coloso amonita. Recuerda capas de mar que ya nadie recuerda.",
        limitation={"id": "colossus", "text": "COLOSO: ocupa 2 espacios de tripulación (camarote doble)."}, primordial=True, sets=["set_piedra", "set_primordiales"]),
    cat("l_tronador", "Tronador", "el Juicio de la Tormenta", "stormcloud_elemental_cat", None, ["storm"], "legendary", "artillero", "bravucon",
        ("TRONADOR — STORM JUDGEMENT FORM", "PERFECT STORM!"),
        shot("Chubasco", "rayo", "storm", 70, 1.5, status="mojado", turns=2, grav=0.3,
             special="Lluvia que Moja 3x3 + 1 rayo que cae y conduce."),
        ult("PERFECT STORM! (完全嵐)", "Lluvia que deja TODO el barco enemigo Mojado + 3 rayos al azar (PRNG) que se encadenan.", dmg=60),
        "Origen de la Tormenta: tus gatos ⚡ +10%; Conducción salta +2 celdas.",
        "★3: 4 rayos en la ultimate.",
        "★5: la lluvia ya no moja tu barco.",
        {"source": "boss:2", "how": "Jefe 2 (La Gárgola Ronroneante): la tormenta permanente toma forma de gato. Duplicados: dos padres que compartan ⚡, Nv20+."},
        None, "Vive entre tormentas de distracción. Truena bajito para advertirte. Luego truena fuerte.",
        limitation={"id": "weather", "text": "TORMENTOSO: su lluvia también Moja 1 celda alrededor de TU camarote (vulnerable a Conducción enemiga)."}, primordial=True, sets=["set_tormenta", "set_primordiales"]),
    cat("l_merlina", "Merlina", "la Arcana", "storybook_ink_cat", None, ["magic"], "legendary", "invocador", "chismoso",
        ("MERLINA — THE END FORM", "THE END!"),
        shot("Y Vivieron… Hundidos", "runa", "magic", 30, 0.8,
             special="Escribe 'FIN' sobre un módulo: tras 2 turnos estalla (150 al módulo). Si el módulo cae antes, invoca un gato de tinta temporal (1 disparo de 40)."),
        ult("THE END! (完)", "Escribe 'FIN' en 3 módulos a la vez.", dmg=150),
        "Origen de la Magia: tus gatos ✨ +10%; Maldito revela también camarotes ocultos.",
        "★3: 'FIN' estalla en 1 turno si el módulo está Maldito.",
        "★5: el gato de tinta dispara 2 veces.",
        {"source": "boss:4", "how": "Jefe 4 (El Arcanista): estaba atrapada en su grimorio. Duplicados: dos padres que compartan ✨, Nv20+."},
        None, "Nació entre márgenes subrayados y cuentos explicados en voz baja. Termina las historias. Las de tus enemigos, rápido.",
        limitation={"id": "delayed", "text": "RETARDO: el daño llega 2 turnos después; el rival puede reparar el módulo para borrar la palabra."}, primordial=True, sets=["set_arcana", "set_primordiales"]),
    cat("l_astraprima", "Astra Prima", "Emperatriz Estelar", "regal_cosmic_cat", None, ["cosmic"], "legendary", "demoledor", "presumido",
        ("ASTRA PRIMA — STELLAR DECREE FORM", "STELLAR DECREE: STARFALL!"),
        shot("Decreto", "orbe_gravitatorio", "cosmic", 90, 1.5, status="ingravido", turns=1, speed=0.7,
             special="Ingrávido en 3x3."),
        ult("STELLAR DECREE: STARFALL! (星の勅令)", "Tras 1 turno de carga, meteoros sobre todo el barco enemigo. Una vez por batalla. Es el ataque del prólogo y del último golpe del capítulo.", dmg=80, uses=1, charge=1),
        "Origen del Cosmos: tus gatos 🌌 +10%; tus pozos de gravedad duran +1 turno.",
        "★3: la carga de la ultimate no se interrumpe.",
        "★5: el Decreto también Revela.",
        {"source": "boss:5", "how": "Jefe 5 (Estrella Errante): cae al mar con la estrella. Duplicados: dos padres que compartan 🌌, Nv20+."},
        None, "Custodia los pergaminos del cielo profundo. Su corona firma sentencias.",
        limitation={"id": "majesty", "text": "MAJESTAD: sin Sala de Invocación viva no puede usar su ultimate."}, primordial=True, sets=["set_estrellas", "set_primordiales"]),

    # ------------------------------------------------------------------ MÍTICOS (2)
    cat("m_raijin", "Raijin", "Heredero del Trueno", "mecha_neon_cat", None, ["storm"], "mythic", "francotirador", "bravucon",
        ("RAIJIN — 雷神 OVERDRIVE", "RAIJIN: THUNDER GOD OVERDRIVE!"),
        shot("Railgun Voltaico", "rayo", "storm", 100, 0.8, pierce=2, grav=0.1, speed=2.0, status="cargado", turns=1,
             special="Atraviesa 2 módulos; si alguno está Mojado, el rayo salta a TODOS los módulos Mojados conectados."),
        ult("RAIJIN: THUNDER GOD OVERDRIVE! (雷神降臨)", "7 railguns en abanico desde el cielo, cada uno perfora 2.", dmg=70),
        "Heredero: con 2+ gatos ⚡ en el barco, sus Conducciones saltan una vez extra (sinergia con Bobina Tesla).",
        "★3: el railgun perfora 3.",
        "★5: Sobrecarga dura 1 turno menos.",
        {"source": "heroic:1", "how": "Premio de la Expedición Heroica 'El Heredero del Trueno' (Reino 14+ con Tormenta descubierta)."},
        "Dicen que el trueno tuvo un heredero y que se aburre mucho.", "Mecha tuxedo con visor magenta. Forjado entre circuitos. No sabe perder ni callarse.",
        limitation={"id": "overload", "text": "SOBRECARGA: después de su ultimate queda Aturdido 2 turnos (las placas se le abren y humea)."}),
    cat("m_singular", "Singularidad", "Eclipse Silente", "nori_lunar_cat", None, ["cosmic"], "mythic", "demoledor", "miedoso",
        ("SINGULARIDAD — EVENT HORIZON FORM", "SINGULARITY: EVENT HORIZON!"),
        shot("Pozo Silencioso", "orbe_gravitatorio", "cosmic", 70, 1.2, status="ingravido", turns=1,
             special="Invisible hasta impactar; atrae escombros en radio 2."),
        ult("SINGULARITY: EVENT HORIZON! (事象の地平線)", "Agujero negro que arranca hasta 4x4 celdas y lanza los escombros contra el núcleo (tope 40% de la estructura). Una vez por batalla.", dmg=250, uses=1, charge=2, cap=0.40),
        "Horizonte: los proyectiles enemigos que pasan a ≤2 celdas de su camarote se curvan (−precisión enemiga).",
        "★3: la carga resiste el primer golpe.",
        "★5: arranca hasta 5x5.",
        {"source": "heroic:2", "how": "Premio de la Expedición Heroica 'Grieta Cósmica' (Reino 37)."},
        "Un gato negro que absorbe la luz. Y los barcos.", "SINGULARITY CHARGING 1/2… y el rival grita: '¡MATEN A ESE YA!'",
        limitation={"id": "charge2", "text": "CARGA 2 TURNOS: 'SINGULARITY CHARGING 1/2 → 2/2' visible para el rival. Golpear su camarote reinicia la carga. Una vez por batalla."},
        sets=["set_rotos"]),

    # ------------------------------------------------------------------ SECRETOS (6) — '???' en el Catdex
    cat("s_maneki", "Mochi Maneki", "la Campana de la Suerte", "mochi_bell_cat", None, ["magic"], "epic", "soporte", "presumido",
        ("MOCHI — DAWN BELL FORM", "LUCKY BELL OF DAWN!"),
        shot("Campanazo", "rafaga", "magic", 35, 1.5, status="aturdido", turns=1, grav=0.0,
             special="Onda sonora circular: Aturde a la tripulación del módulo 1 turno y da Suerte (+10% crítico) a tu equipo 2 turnos."),
        ult("LUCKY BELL OF DAWN! (招き鐘)", "El próximo disparo de cada aliado es crítico garantizado.", dmg=0),
        "Maneki: en el Cat's Gambit suma +3/+2/+1 puntos de probabilidad a las mesas x2/x5/x20 (balance.gambit.cat_mods.maneki).",
        "★3: Suerte dura 3 turnos.",
        "★5: su cascabel suena cuando un tiro tuyo va a ser crítico (vista previa).",
        {"source": "secret", "how": "Ruta A: Resonancia de dos gatos con oficio Banquero, ambos Nv15+ → entra al bucket '???'. Ruta B: rescata 10 Gatos Callejeros (microevento): el 10.º es Mochi."},
        "Dicen que aparece cuando dos gatos que cuidan el oro se ponen de acuerdo… o cuando ya rescataste a demasiados callejeros.",
        "Fue la primera en responder cuando el Archivo pidió guardianes tiernos. Su cascabel suena cuando estás a un detalle de ganar.",
        secret=True, gambit_mod="maneki"),
    cat("s_caos", "Pixel Glitch", "el Gato del Caos", "neon_glitch_cat", None, ["storm", "cosmic"], "epic", "francotirador", "travieso",
        ("PIXEL GLITCH — FATAL ERROR FORM", "FATAL ERROR!"),
        shot("Error 404: Casco No Encontrado", "objetivo", "storm", 80, 1.0,
             special="Se teletransporta y BORRA un bloque 2x2 del casco elegido (ignora cobertura). El elemento del daño es aleatorio entre los 7 (PRNG con semilla)."),
        ult("FATAL ERROR! (致命的エラー)", "'Borra' 3 bloques 2x2 al azar del barco enemigo. Una vez por batalla.", dmg=80, uses=1),
        "Caos: habilita en el Cat's Gambit la mesa x50 'todo o nada' (balance.gambit.cat_mods.caos).",
        "★3: puedes elegir 1 de 2 elementos sorteados.",
        "★5: el bloque borrado es 3x2.",
        {"source": "secret", "how": "Ruta A: Resonancia cuya unión incluya ⚡ y 🌌 mientras hay un Evento Flash activo → bucket '???'. Ruta B: microevento 'Error 404' (tras descubrir Cósmico): atrapa 5 glitches en 60 s → duelo → se une."},
        "Algo se mueve entre píxeles cuando el cielo se rompe.", "Apareció dentro de un error de interfaz y decidió quedarse. No reportes el bug.",
        limitation={"id": "unstable", "text": "INESTABLE: cada disparo es de un elemento aleatorio (ruleta visible en el retrato)."},
        secret=True, gambit_mod="caos"),
    cat("s_noctis", "Velo Noctis", "Capitana de la Mascarada", "masquerade_phantom_cat", None, ["water", "magic"], "legendary", "controlador", "presumido",
        ("VELO NOCTIS — THOUSAND FACES FORM", "MASQUERADE: THOUSAND FACES!"),
        shot("Danza de los Mil Rostros", "runa", "magic", 70, 1.0,
             special="Crea 3 máscaras-señuelo sobre tu barco (la IA les dispara; cada una absorbe 1 golpe) y lanza una daga-runa teledirigida."),
        ult("MASQUERADE: THOUSAND FACES! (千の仮面)", "2 turnos: todos los tiros enemigos apuntan a señuelos; su daga real explota en el núcleo x1.5.", dmg=90),
        "Bandera Negra: +40% chatarra si va en el Merodeador (se suma al perk del barco).",
        "★3: 4 señuelos.",
        "★5: los señuelos que reciben un golpe lo devuelven al 30%.",
        {"source": "secret", "how": "Historia: tras vencer al Primer Mar, la rival se une a tu tripulación ('me debes una')."},
        "Algunas rivales no se vencen: se convencen.", "Antifaz veneciano, encaje morado y cero respeto por la propiedad ajena. Te robó la mitad del capítulo. Te salva al final.",
        secret=True),
    cat("s_sonata", "Sonata Prima", "la Primera Nota", "sonata_prima_cat", None, ["magic", "cosmic", "storm"], "mythic", "soporte", "leal",
        ("SONATA PRIMA — GRAN FINALE FORM", "GRAN FINALE!"),
        shot("Crescendo", "rafaga", "magic", 30, 1.5, grav=0.0,
             special="Suma 1 nota por cada disparo aliado desde su último disparo (máx. 4). Daño 30 + 25 x notas; con 4 notas golpea TODOS los módulos enemigos a x0.5."),
        ult("GRAN FINALE! (大団円)", "Acorde que golpea todos los módulos enemigos (60 c/u; tope 35% de estructura).", dmg=60),
        "Metrónomo: mientras viva, la recarga de todos tus gatos es −1 (mín. 0).",
        "★3: empieza con 1 nota.",
        "★5: Gran Finale cura 10% a tus módulos.",
        {"source": "secret", "how": "Ruta A: Resonancia cuya unión cubra ✨, 🌌 y ⚡ con ambos padres Nv30+ → bucket '???'. Ruta B: Santuario Gatuno Antiguo (secreto de las Ruinas Arcanas): vence a 'La Orquesta Muda'."},
        "En las ruinas, una partitura espera a quien conozca la magia, las estrellas y el trueno.",
        "Nació del primer acorde que ordenó el caos del Archivo Vivo. Tres elementos. Cero explicaciones. '¿QUÉ PUTAS TUVE QUE CRUZAR PARA SACAR ESO?'",
        secret=True),
    cat("s_lumen", "Lumen", "la Fotógrafa del Recuerdo", "lumen_lens_cat", None, ["fire", "water", "nature"], "legendary", "controlador", "curioso",
        ("LUMEN — ETERNAL EXPOSURE FORM", "ETERNAL EXPOSURE!"),
        shot("Instantánea Eterna", "rayo", "fire", 45, 1.5, status="sellado", turns=1, grav=0.0,
             special="Flash: congela en el tiempo la zona 3x3 fotografiada (módulos Sellados 1 turno)."),
        ult("ETERNAL EXPOSURE! (永遠の一瞬)", "Repite exactamente el último ataque aliado (no repite ultimates de 'una vez por batalla').", dmg=0),
        "Álbum: guarda la foto del mejor golpe de cada batalla en 'Momentos' del Catdex.",
        "★3: el flash cubre 4x4.",
        "★5: la repetición hace x1.25.",
        {"source": "secret", "how": "Ruta A: Resonancia cuya unión cubra 🔥, 💧 y 🌿 con ambos padres ★3+ → bucket '???'. Ruta B: registra 40 especies en el Catdex y llega sola ('vine a tomarle foto a tu colección')."},
        "Llega cuando tu colección vale la pena retratarse.",
        "Captura recuerdos antes de que Distraxia los borre. Guarda la luz de los tres primeros elementos.",
        secret=True),
    cat("s_eclipse", "Eclipse", "la que Apaga el Sol", "selene_moonlit_cat",
        T(hue=0, sat=0.2, bright=0.35, overlay="#ffd974", alpha=0.25, decal="corona", aura=["#0d110f", "#ffd974", "#ff6a1a"]),
        ["fire", "cosmic"], "legendary", "francotirador", "miedoso",
        ("ECLIPSE — BLACK CORONA FORM", "TOTAL ECLIPSE!"),
        shot("Corona Negra", "rayo", "fire", 90, 1.0, status="ingravido", turns=1, grav=0.2,
             special="Invisible para el rival (sin trayectoria); aplica Ardiendo + Ingrávido."),
        ult("TOTAL ECLIPSE! (皆既日食)", "2 turnos: el rival dispara sin vista previa y sin críticos; tu siguiente disparo x2.", dmg=0),
        "Penumbra: +20% daño a gatos enemigos Expuestos.",
        "★3: el eclipse dura 3 turnos.",
        "★5: Corona Negra perfora 1 capa.",
        {"source": "secret", "how": "Ruta A (CHARLA): Resonancia con Solar + cualquier padre 🌌, uno de ellos Nv20+ → bucket '???'. Ruta B: gana una batalla con Solar y Lunita en la tripulación durante el evento Estrella Fugaz."},
        "Dicen que aparece cuando un gato de sol y uno de luna pelean del mismo lado.",
        "La luna se puso enfrente del sol y se quedó ahí. A propósito.",
        secret=True),
]
