# -*- coding: utf-8 -*-
"""Eventos (micro, flash, heroicos, especiales), extras de expansiones, automatizaciones extra e historia."""

MICRO_EVENTS = [
    {"id": "pez_dorado", "name": "¡Pez Dorado!", "duration_s": 45, "trigger": "kl:3 (el primero está guionizado tras la misión H07)", "weight": 3,
     "task": "Un pez dorado cruza la costa de la isla: haz clic sobre él → minijuego de 20 s (revienta 8 burbujas que suben).",
     "reward": "Comida = 5 min de tu producción de comida (+ Ronroneo 0.5 min afín a granjas).", "note": "CHARLA: 'Golden Fish 00:45'."},
    {"id": "gato_callejero", "name": "Gato Callejero", "duration_s": 120, "trigger": "kl:4", "weight": 3,
     "task": "Un gato desconocido aparece escondido entre tus hábitats (silueta con '?'). Encuéntralo (clic) → te reta a un Duelo de Gatos 1v1.",
     "reward": "+15 Orbes de Alma (de una especie aleatoria que tengas; si sale una que no tienes, su ficha pasa a 'Rumor'). El 10.º callejero es Mochi Maneki (secreto).", "note": "CHARLA: 'RUNAWAY CAT 02:00'."},
    {"id": "cangrejo_chatarrero", "name": "Cangrejo Chatarrero", "duration_s": 90, "trigger": "kl:5", "weight": 2,
     "task": "Un cangrejo cruza la playa cargando tornillos: hazle clic 5 veces antes de que llegue al agua.",
     "reward": "Chatarra = la de 1 victoria en tu etapa frontera."},
    {"id": "botella_mensaje", "name": "Botella con Mensaje", "duration_s": 180, "trigger": "expansion:1", "weight": 2,
     "task": "Una botella flota junto al muelle: ábrela.",
     "reward": "Pista de un secreto (su ficha pasa a 'Rumor') o, si ya tienes todas las pistas, 1 gema (20%) o Doblones = 2 min de ingreso."},
    {"id": "lluvia_pescaditos", "name": "Lluvia de Pescaditos", "duration_s": 40, "trigger": "kl:8", "weight": 2,
     "task": "Llueven peces sobre la isla: atrapa todos los que puedas (clic).",
     "reward": "Comida = 4 s de producción por pez atrapado (máx. 40 peces)."},
    {"id": "ovillo_rodante", "name": "Ovillo Rodante", "duration_s": 60, "trigger": "kl:6", "weight": 2,
     "task": "Un ovillo rueda por la isla y tus gatos lo persiguen. Atrápalo antes de que caiga al mar.",
     "reward": "Momentum +0.1 y +10 de medidor de ultimate inicial en tu próxima batalla."},
    {"id": "gato_dormido_canon", "name": "Gato Dormido en el Cañón", "duration_s": 90, "trigger": "first_yard_job", "weight": 2,
     "task": "Un gato se durmió dentro de un cañón del astillero. Despiértalo (clic) sin dispararlo… o dispáralo (es tu decisión; no le pasa nada, cae en una caja).",
     "reward": "Ronroneo +2 min afín al Astillero."},
    {"id": "comerciante", "name": "Don Ganzúa, el Comerciante", "duration_s": 180, "trigger": "boss:1", "weight": 1,
     "task": "Un bote sin cara (solo se le ven los ojos) atraca: ofrece 2 cambios de excedentes.",
     "reward": "Cambios: Doblones (10 min de ingreso) → 1 Orbe Prisma · 5 Chatarra → 1 Plano · 20 Cristales de un elemento → 15 de otro. Máx. 1 de cada por visita.", "note": "Convierte excedentes (regla: no hay monedas muertas)."},
    {"id": "burbuja_resonancia", "name": "Burbuja de Resonancia", "duration_s": 60, "trigger": "resonance_running", "weight": 2,
     "task": "Una burbuja con un corazón sale del Santuario y flota por la isla: revientala.",
     "reward": "Ronroneo 1.5 min afín a la Resonancia en curso."},
    {"id": "meteorito_chiquito", "name": "Meteorito Chiquito", "duration_s": 60, "trigger": "element:cosmic", "weight": 2,
     "task": "Cae una piedrita brillante en una expansión: encuéntrala.",
     "reward": "Cristales 🌌 x3."},
    {"id": "error_404", "name": "Error 404", "duration_s": 60, "trigger": "element:cosmic (una sola vez hasta capturarlo)", "weight": 1,
     "task": "Glitches aparecen sobre la isla: atrapa 5 en 60 s → Duelo contra Pixel Glitch.",
     "reward": "Pixel Glitch, el Gato del Caos (secreto). Si fallas, vuelve más adelante."}
]
MICRO_RULES = [
    "Aparecen solos (sin aceptar). Reloj ROJO pequeño; no se pausan ni se extienden.",
    "Cadencia: 1 microevento cada 6-10 min de juego ACTIVO (input en los últimos 60 s), nunca durante una batalla, un modal T3/T4 o un jefe: esperan.",
    "Nunca el mismo dos veces seguidas; pesos por 'weight' entre los elegibles por su trigger.",
    "Premios indexados a la producción (segundos de ingreso), por eso valen igual en el minuto 10 que en la hora 5. No están en sim.py (balance.meta.not_simulated).",
    "Si lo ignoras, se va sin castigo."
]

FLASH_TYPES = [
    {"id": "migracion_leviatan", "name": "Migración del Leviatán", "presage": "El mar huele a sardina gigante…",
     "twist": "Todas las cosechas que TERMINEN durante el evento dan x15 comida (CHARLA). Aparecen barcos-ballena en tu etapa frontera.",
     "bonus": "Si las 3 victorias son contra barcos-ballena: pieza exclusiva 'Arpón del Leviatán' (tipo de arma, una sola vez)."},
    {"id": "tormenta_horizonte", "name": "Tormenta en el Horizonte", "presage": "Truena… pero no hay nubes.",
     "twist": "Los enemigos traen chispas: cada victoria suelta 1 Fragmento de Tormenta '???' (lore antes de descubrir Tormenta; si ya la tienes: cristales ⚡).",
     "bonus": "3 Fragmentos → la ficha de Tronador pasa a 'Rumor'."},
    {"id": "demolicion_expres", "name": "Demolición Exprés", "presage": "Un cartel flota: 'SE BUSCA DEMOLEDOR'.",
     "twist": "Puzles de demolición: 3 barcos-reto que tienes que hundir en 3 turnos (3 disparos de gato + sus andanadas). La solución existe: colapso, polvorín o brecha.",
     "bonus": "+1 Plano por puzle resuelto al primer intento."},
    {"id": "niebla_distraxia", "name": "Niebla de Distraxia", "presage": "Todo se ve borroso… ¿de qué estábamos hablando?",
     "twist": "Batallas con niebla: la vista previa de trayectoria se corta al 50% para todos (Linterna Espíritu la ignora).",
     "bonus": "Lore de Distraxia + Orbes x10 de un gato de la tripulación."},
    {"id": "sobrecarga_volcanica", "name": "Sobrecarga Volcánica", "presage": "La Isla Volcánica tose humo.",
     "twist": "Durante 8 min: gatos 🔥 hacen x3 de daño, pero tus granjas producen −50% comida (decisión horrible y deliciosa: 'A LA MIERDA LAS GRANJAS').",
     "bonus": "Cristales 🔥 x10."},
    {"id": "mar_de_cristal", "name": "Mar de Cristal", "presage": "El agua se puso dura. Y brillante.",
     "twist": "Todos los barcos enemigos están hechos de cristal (x1.5 contra Tierra, quebradizos).",
     "bonus": "Cristales 🪨 x10."},
    {"id": "marea_fantasma", "name": "Marea Fantasma", "presage": "Las olas regresan… sin hacer ruido.",
     "twist": "Los barcos que hundes regresan UNA vez como fantasmas (30% de vida, casco de hueso) y hay que hundirlos otra vez. El último es el Capitán Fantasma.",
     "bonus": "Primera vez: Escudo Sacrificial (tipo de escudo) + pista de Velo Noctis. Después: Orbes x10."},
    {"id": "diluvio", "name": "Diluvio", "presage": "Va a llover. Mucho. Sobre todo.",
     "twist": "Ambos barcos están Mojados siempre: la Conducción es una fiesta (para los dos).",
     "bonus": "Cristales ⚡ x10."},
    {"id": "luna_resonancia", "name": "Luna de Resonancia", "presage": "Sale una luna rosa… tus gatos se ponen raros.",
     "twist": "Las Resonancias que TERMINEN durante el evento traen mutación garantizada (de combate, ver Mutaciones).",
     "bonus": "Orbe Prisma x3."},
    {"id": "lluvia_polvo_estelar", "name": "Lluvia de Polvo Estelar", "presage": "Brillitos caen del cielo. Pican.",
     "twist": "Cada victoria suelta Polvo Cósmico '???'; con 3 victorias tu Catdex muestra la silueta de Astra Prima (Rumor). Si ya tienes Cósmico: cristales 🌌.",
     "bonus": "Cristales del elemento más alto que tengas x10."},
    {"id": "estrella_fugaz", "name": "Estrella Fugaz", "presage": "¡Algo cayó en una de tus islas!",
     "twist": "Antes de las batallas: tienes 5:00 (rojo) para encontrar la estrella caída en tu isla (clic). Si la encuentras, la batalla del evento es contra su guardián.",
     "bonus": "Orbes de Meteoro x50 (o 5% de Meteoro completo si no lo tienes); primera vez: arma Starbreaker. Si ganas con Solar y Lunita a bordo: Eclipse (secreto)."}
]

FLASH_SCHEDULE = [
    {"kl": 5, "type": "migracion_leviatan"}, {"kl": 7, "type": "tormenta_horizonte"}, {"kl": 9, "type": "demolicion_expres"},
    {"kl": 11, "type": "niebla_distraxia"}, {"kl": 13, "type": "sobrecarga_volcanica"}, {"kl": 15, "type": "mar_de_cristal"},
    {"kl": 17, "type": "migracion_leviatan"}, {"kl": 19, "type": "marea_fantasma"}, {"kl": 21, "type": "diluvio"},
    {"kl": 23, "type": "demolicion_expres"}, {"kl": 25, "type": "luna_resonancia"}, {"kl": 27, "type": "niebla_distraxia"},
    {"kl": 29, "type": "lluvia_polvo_estelar"}, {"kl": 31, "type": "sobrecarga_volcanica"}, {"kl": 33, "type": "estrella_fugaz"},
    {"kl": 35, "type": "marea_fantasma"}, {"kl": 37, "type": "mar_de_cristal"}, {"kl": 39, "type": "diluvio"},
    {"kl": 41, "type": "estrella_fugaz"}, {"kl": 43, "type": "luna_resonancia"}, {"kl": 45, "type": "migracion_leviatan"}
]
FLASH_RULES = [
    "Disparador: balance.events.flash (cada 2 niveles de Reino desde el 5). Tipo según FLASH_SCHEDULE (en la Marea Nueva/NG+ el orden se baraja con semilla).",
    "Aparece un PRESAGIO (banner en la HUD, sin reloj): tienes hasta 10 min de juego para aceptarlo o posponerlo; mientras tanto puedes prepararte. Al aceptar arranca el reloj ROJO.",
    "Reloj ROJO sagrado: duración balance.events.flash.duration_s (480 s). No se pausa, no se extiende, ni con gemas. Corre en tiempo de JUEGO (si cierras el juego se congela: nunca se pierde un evento por cerrar la pestaña).",
    "Tarea base: ganar balance.events.flash.battles_needed (3) batallas. Botín de batalla x balance.events.flash.loot_mult (1.5).",
    "Premio base: balance.events.flash.gems (1) + crystals (6) del elemento del evento + Ronroneo balance.ronroneo.base_min.flash_event. Más el bonus del tipo.",
    "Nunca se superponen dos relojes rojos: si un Presagio coincide con otro evento activo, espera.",
    "Nunca interrumpe a un jefe. Si fallas, lo ganado por batalla se queda (piso fijo)."
]

HEROICS = [
    {"id": "heroica_1", "balance": "events.heroic[0]", "name": "El Heredero del Trueno", "trigger": "Reino ≥ balance.events.heroic[0].kl (14) Y Tormenta descubierta (jefe 2).",
     "duration": "balance.events.heroic[0].duration_s (1500 s = 25:00), ROJO sagrado",
     "track": "🚩━━●━━●━━●━━●━━●━━●━━🏆",
     "nodes": [
         {"n": 1, "task": "Recolecta Doblones = 4 min de tu ingreso (medido al aceptar).", "system": "isla", "reward": "Comida = 3 min de producción"},
         {"n": 2, "task": "Gana 2 batallas con al menos un gato ⚡ en la tripulación.", "system": "combate", "victories": 2, "reward": "Cristales ⚡ x6"},
         {"n": 3, "task": "Pesca comida = 3 min de tu producción.", "system": "muelle", "reward": "Orbes de Raijin x10 (se guardan aunque aún no lo tengas)"},
         {"n": 4, "task": "Destruye 12 módulos enemigos.", "system": "combate", "reward": "Planos x2"},
         {"n": 5, "task": "Sube 5 niveles en total a tus gatos.", "system": "alimentar", "reward": "Gemas x2"},
         {"n": 6, "task": "Gana 2 batallas cualesquiera.", "system": "combate", "victories": 2, "reward": "Orbe Prisma x5"},
         {"n": 7, "task": "FINAL: derrota a Raijin (batalla especial 'Nube de Guerra').", "system": "jefe", "victories": 1, "reward": "RAIJIN (Mítico) + balance gems (5)"}
     ],
     "safety": "Umbral seguro: con 5 de 7 nodos completados recibes Orbes de Raijin x30 aunque no llegues al final.",
     "sprint": "Sprint: nodos 1-3 en menos de 8:00 → premios de esos nodos x2 y Reliquia 'Corona del Trueno'.",
     "retry": "Si se acaba el reloj, la Heroica regresa 3 niveles de Reino después como 'Revancha Heroica' conservando los nodos hechos."},
    {"id": "heroica_2", "balance": "events.heroic[1]", "name": "Grieta Cósmica", "trigger": "Reino ≥ balance.events.heroic[1].kl (37) (Cósmico ya descubierto por el jefe 5).",
     "duration": "1500 s (25:00), ROJO sagrado",
     "track": "🚩━━●━━●━━●━━●━━●━━●━━🕳️",
     "nodes": [
         {"n": 1, "task": "Recolecta Doblones = 4 min de tu ingreso.", "system": "isla", "reward": "Comida = 3 min"},
         {"n": 2, "task": "Termina 1 Resonancia con al menos un padre 🌌 (se acelera con Ronroneo).", "system": "resonancia", "reward": "Orbe Prisma x5"},
         {"n": 3, "task": "Gana 2 batallas con al menos un gato 🌌.", "system": "combate", "victories": 2, "reward": "Cristales 🌌 x8"},
         {"n": 4, "task": "Sube de estrella a cualquier gato O sube 5 niveles en total.", "system": "estrellas", "reward": "Gemas x2"},
         {"n": 5, "task": "Destruye 15 módulos.", "system": "combate", "reward": "Planos x3"},
         {"n": 6, "task": "Gana 2 batallas cualesquiera.", "system": "combate", "victories": 2, "reward": "Orbes de Singularidad x10"},
         {"n": 7, "task": "FINAL: La Grieta ('¡MATEN A ESE YA!').", "system": "jefe", "victories": 1, "reward": "SINGULARIDAD (Mítico) + 5 gemas"}
     ],
     "safety": "5 de 7 nodos → Orbes de Singularidad x30.",
     "sprint": "Nodos 1-3 en menos de 8:00 → premios x2.",
     "retry": "Revancha Heroica 3 niveles después (post-capítulo si hace falta)."}
]
HEROIC_NOTE = "Las victorias de los nodos suman exactamente balance.events.heroic[].victories_needed (2 + 2 + 1 = 5). Los nodos económicos se miden en MINUTOS de tu producción al aceptar, así que nunca son un muro."

BLACK_FLAG = {"id": "bandera_negra", "balance": "events.black_flag", "name": "Bandera Negra",
              "trigger": "Reino ≥ balance.events.black_flag.kl (15).", "duration": "1200 s (20:00) ROJO",
              "task": "Gana 5 batallas contra la flota de Velo Noctis (5 barcos con bandera negra que aparecen como etapas especiales, poder = tu etapa frontera; el 5.º es su buque insignia).",
              "reward": "Barco Merodeador gratis (si ya lo compraste: Reliquia 'Antifaz de Noctis' + 2 gemas). Siempre: Reliquia 'Antifaz de Noctis'.",
              "lines": ["NOCTIS: Cinco barcos. Veinte minutos. Si ganas, te regalo uno. Si pierdes… me quedo con tu dignidad.",
                        "NOCTIS (al perder su insignia): Tch. Quédatelo. Ya me estaba aburriendo de ese barco."]}

STORY_EVENTS = [
    {"id": "algo_viene", "name": "Algo viene", "trigger": "balance.elements.magic.unlock (kl:24)", "clock": "Presagio sin reloj; la batalla del Heraldo no tiene límite de tiempo.",
     "content": "Una grieta se abre sobre la isla; el Heraldo del Arcanista llega con un barco que brilla. Batalla de historia (story_heraldo) → MAGIA."},
    {"id": "barco_vacio", "name": "A VOID SHIP HAS ENTERED YOUR WORLD", "trigger": "kl:38 (o al llegar a la etapa 6-5, lo que pase primero)", "clock": "ROJO 14:59",
     "content": "Batalla imposible (event_vacio). El daño hecho da Fragmentos del Vacío (1 por cada 15%, máx. 3). Ronroneo de jefe si haces ≥45%."},
    {"id": "revancha_patito", "name": "Hace mucho tiempo, en una balsa…", "trigger": "kl:36", "clock": "sin reloj",
     "content": "Vuelve el Patito Pirata. Lo borras con un número ridículo (overkill (SP/EP)^3 x 1000). Nostalgia + logro."}
]

EXPANSION_EXTRAS = {
    1: {"id": "bosque_costero", "biome": "forest", "region": {"cx": 14, "cy": 24, "r": 5},
        "secret": {"name": "Santuario Sellado", "condition": "Reino 5 (se ve sellado desde que limpias el terreno)", "content": "Duelo contra el Guardián Musgoso (Musgo pirata).", "reward": "2 gemas + pista de Lumen (Rumor)"},
        "visual": "Pinos costeros, hongos, luciérnagas de noche.", "opensDesign": "Cadena del Criador (misiones). Hábitat de Naturaleza (bioma bosque)."},
    2: {"id": "acantilado_rocoso", "biome": "cliff", "region": {"cx": 22, "cy": 13, "r": 5},
        "secret": {"name": "Fósil en la Pared", "condition": "Al terminar de limpiar", "content": "Un fósil incrustado: clic 10 veces para sacarlo.", "reward": "2 gemas + 5 orbes de Gea (se guardan)"},
        "visual": "Rocas, gaviotas, ruinas de piedra con huellas de gato.", "opensDesign": "2.º Constructor; ruinas de Tierra (puerta a la Zona 2)."},
    3: {"id": "isla_volcanica", "biome": "volcano", "region": {"cx": 31, "cy": 22, "r": 5},
        "secret": {"name": "Forja Dormida", "condition": "Al terminar de limpiar", "content": "Una forja apagada: enciéndela con un gato 🔥 de nivel 10+.", "reward": "2 gemas + tipo de arma Mortero de Magma"},
        "visual": "Lava, obsidiana, géiseres; los gatos de fuego se ven felices aquí.", "opensDesign": "2.ª ranura de Resonancia; Forja de cañones; Ancla (módulo)."},
    4: {"id": "puerto_mareas", "biome": "ghost", "region": {"cx": 23, "cy": 31, "r": 5},
        "secret": {"name": "Botella del Faro", "condition": "Al terminar de limpiar", "content": "Una botella con una carta firmada con un antifaz.", "reward": "2 gemas + lore + pista de Velo Noctis (Rumor)"},
        "visual": "Puerto pálido con niebla (bioma 'ghost'), faroles, muelles largos; aquí zarpan las expediciones.", "opensDesign": "Expediciones; 2.º dique del astillero; Banco del Reino offline +2 h."},
    5: {"id": "glaciar_bigote", "biome": "ice", "region": {"cx": 13, "cy": 14, "r": 4.5},
        "secret": {"name": "Gato en el Hielo", "condition": "Al terminar de limpiar", "content": "Un gato congelado (Fanguito pirata) sostiene un cañón raro. Descongélalo con un gato 🔥.", "reward": "2 gemas + tipo de arma Lanzaescarcha"},
        "visual": "Hielo, focas-gato de nieve, auroras.", "opensDesign": "Granjas +25% (balance bonus food), escudos −20% costo, parcelas de cultivo largas; Torre Elemental (módulo)."},
    6: {"id": "ruinas_arcanas", "biome": "ruins", "region": {"cx": 31, "cy": 31, "r": 4.5},
        "secret": {"name": "Santuario Gatuno Antiguo", "condition": "Al terminar de limpiar (debajo de unas rocas)", "content": "Batalla especial 'La Orquesta Muda' (secret_orquesta).", "reward": "4 gemas + Sonata Prima (secreto) + lore del Archivo Vivo"},
        "visual": "Columnas violeta con runas, libros flotando, ORQUÍDEA REAL.", "opensDesign": "3.ª Resonancia, astillero del Bajel Arcano, secretos."},
    7: {"id": "arrecife_prismatico", "biome": "reef", "region": {"cx": 13, "cy": 32, "r": 4.5},
        "secret": {"name": "Concha Espejo", "condition": "Al terminar de limpiar", "content": "Una concha gigante que refleja tu barco.", "reward": "2 gemas + Escudo Espejo"},
        "visual": "NUEVO BIOMA 'reef': top #F7B2C8/#9FE6E0, side #3D8C9E, sideDark #1C3A51, edge #FFFFFF; corales arcoíris.", "opensDesign": "Mina de Orbes Prisma; +1% extra por especie del Catdex."},
    8: {"id": "atolon_estelar", "biome": "cosmic", "region": {"cx": 34, "cy": 11, "r": 4},
        "secret": {"name": "Faro del Primer Mar", "condition": "Al terminar de limpiar", "content": "Un faro apagado que apunta a la Zona 6.", "reward": "4 gemas + escena: el faro se enciende y señala al Leviatán"},
        "visual": "Isla flotando sobre el agua, peces de luz, cielo glitch.", "opensDesign": "Núcleo Celestial, Atún de Nebulosa, 'muelle hacia el Leviatán' (atajo narrativo; NO es requisito del jefe final)."}
}

AUTOMATION_EXTRAS = [
    {"kl": 1, "id": "ronroneo_auto", "name": "Auto-Ronroneo", "design": True, "rule": "El Ronroneo que ganas se aplica solo al reloj verde FIJADO (📌) o, si no hay, al que esté más cerca de terminar. Lo que sobra va a la reserva (tope balance.ronroneo.pool_cap)."},
    {"kl": 1, "id": "asalto_rapido", "name": "Asalto Rápido", "design": True, "rule": "En etapas ya ganadas con PoderBarco/PoderEnemigo ≥ 2.5 (p ≥ 0.95 según balance.combat.win_formula): botón que resuelve la batalla en 5 s con animación resumen. Botín normal de etapa ya ganada (farm_stage_mult)."},
    {"kl": 10, "id": "compra_x10", "name": "Comprar x10 / MAX", "design": True, "rule": "Botones x10 y MAX en mejoras de granja y alimentar (sentir la escala)."},
    {"kl": 1, "id": "boss_analysis", "name": "Análisis de Jefe", "design": True, "rule": "Cada derrota contra un jefe suma balance.combat.boss_analysis_per_defeat (20%). 20%: ves la vida de cada fase · 40%: punto débil revelado · 60%: telegrafía 1 turno antes · 80-100%: el poder del jefe baja hasta balance.combat.boss_analysis_power_bonus_max (25%)."}
]

STORY_BEATS = [
    {"id": "b00_prologo", "time": "0:00", "trigger": "nueva partida", "style": "NEÓN GLITCH + MANGA TINTA", "title": "En algún momento del futuro…",
     "lines": [["CAPTION", "EN ALGÚN MOMENTO DEL FUTURO…"],
               ["LUZTERNA", "¿Ves esa cosa enorme? Sí, esa. La que tapa el cielo. Bueno: mantén… y suelta."],
               ["SISTEMA", "(El jugador mantiene y suelta: ASTRA PRIMA ★6 — STELLAR DECREE: STARFALL. El barco gigante se parte en tres en viñetas.)"],
               ["PERIÓDICO", "¡EXTRA! ¡EXTRA! UN GATO PARTE UN BARCO EN TRES"],
               ["CAPTION", "MUCHO ANTES…"]]},
    {"id": "b01_despertar", "time": "0:50", "trigger": "fin del prólogo", "style": "COZY ISLA", "title": "Una balsa, una palmera y un gato dormido",
     "lines": [["LUZTERNA", "Ey. Ey. EY. Despierta, grumete. No, tú no: el gato. Bueno, los dos."],
               ["LUZTERNA", "Soy Luzterna. Capitana fantasma, ex-farera del Archivo y, desde hoy, tu jefa. No preguntes por qué soy transparente."],
               ["LUZTERNA", "Ese que ronca en la caja se llama Canelo. Tócalo. Con cariño… o no, tú sabrás."]]},
    {"id": "b02_nombre", "time": "1:30", "trigger": "H01", "style": "COZY ISLA", "title": "¿Cómo se llama?",
     "lines": [["LUZTERNA", "¿Le vas a cambiar el nombre? Si le pones 'Michi' no te juzgo. Mucho."]]},
    {"id": "b03_oro", "time": "2:00", "trigger": "primer toque a hábitat", "style": "COZY ISLA", "title": "Doblones",
     "lines": [["LUZTERNA", "Eso que brilla son Doblones. Los gatos los producen nomás por existir. Ojalá yo."]]},
    {"id": "b04_pescado", "time": "2:15", "trigger": "H03", "style": "COZY ISLA", "title": "Algo huele a pescado",
     "lines": [["LUZTERNA", "Los gatos comen. Mucho. Siembra sardinas en el muelle."],
               ["LUZTERNA", "Tarda poquito. Puedes esperar… o puedes hacer algo útil mientras. Esa es la regla de este mar: esperas o sigues jugando."]]},
    {"id": "b05_nam", "time": "3:15", "trigger": "H04", "style": "COZY ISLA", "title": "¡ÑAM!",
     "lines": [["LUZTERNA", "¿Viste? Creció. Y ojo: aquí subir de nivel no es '+27 de ataque'. Es 'en dos niveles su bola de pelo EXPLOTA'."]]},
    {"id": "b06_patito", "time": "4:30", "trigger": "H05", "style": "NOIR OCEÁNICO → ANIME INFERNO", "title": "Ahora haz que valga la pena",
     "lines": [["LUZTERNA", "¿Ves ese patito de hule? Es un barco. Es pirata. Y nos está viendo feo."],
               ["PATITO", "¡Cuac! ¡Esta es mi bahía! ¡Cuac!"],
               ["LUZTERNA", "Ah, sí: tus gatos se transforman en batalla. Cosas del Archivo. No preguntes. Se ve chingón."],
               ["LUZTERNA", "Arrastra desde el gato, apunta… y suelta. Si fallas, no pasa nada. Bueno, sí pasa: el pato se ríe."],
               ["PATITO", "¡CUAAAAC!"],
               ["LUZTERNA", "Aunque pierdas, avanzas. Pero no perdiste. Mira nomás ese botín."]]},
    {"id": "b09_nube", "time": "7:00", "trigger": "H07", "style": "DIARIO DEL MAR", "title": "Eso no era una nube",
     "lines": [["SISTEMA", "(El cielo se oscurece un segundo; la música se corta.)"],
               ["LUZTERNA", "…Eso no era una nube."],
               ["LUZTERNA", "Era Distraxia. La Niebla del Olvido. Larga historia. Te la cuento cuando tengas un barco que no sea de cartón."]]},
    {"id": "b07_resonancia", "time": "8:00", "trigger": "H06", "style": "ORQUÍDEA REAL", "title": "Tus gatos se fueron a invocar otro",
     "lines": [["LUZTERNA", "El Santuario de Resonancia: juntas a dos gatos y… se van a invocar otro gatito. No preguntes cómo. Es sagrado. Y privado."],
               ["CAPTION", "Canelo y Brote se fueron a hacer quién sabe qué…"],
               ["LUZTERNA", "Tarda minuto y medio. Puedes esperar… o ir a romperle la madre a alguien mientras tanto. Cada victoria baja el reloj verde."]]},
    {"id": "b08_pimenton", "time": "9:30", "trigger": "K07", "style": "EDITORIAL SUIZO", "title": "¡Mira lo que salió!",
     "lines": [["CAPTION", "Canelo y Brote se fueron a invocar otro… y volvieron con ESTO."],
               ["LUZTERNA", "¿Un gato de fuego Y planta? ¿Un RARO a la primera? Qué suertudo. No te acostumbres. (Sí acostúmbrate.)"],
               ["LUZTERNA", "Ahora junta fuego con agua y espera a que crezcan… dicen que de ahí sale vapor. Y a veces, algo MUCHO peor."]]},
    {"id": "b10_bigotes", "time": "~28:00", "trigger": "H08", "style": "MANGA TINTA → DIARIO DEL MAR", "title": "El Capitán Bigotes Rotos",
     "lines": [["BIGOTES", "¡Arrr! ¿Una balsa? ¿Con TRES gatos? Esto va a ser más fácil que robarle el pescado a un gato dormido."],
               ["LUZTERNA", "Tiene barriles de pólvora en la cubierta. Yo nomás digo."],
               ["BIGOTES", "Bueno… quédate el fósil. Muerde."],
               ["LUZTERNA", "¿Un fósil VIVO en la bodega? Ese pirata no sabía lo que tenía. Tú tampoco, pero tú sí lo vas a usar."],
               ["SISTEMA", "NUEVO ELEMENTO DESCUBIERTO: TIERRA 🪨 · Gea, Corazón de Piedra se une."]]},
    {"id": "b11_noctis", "time": "~31:00", "trigger": "H09", "style": "ORQUÍDEA REAL", "title": "Una máscara en el horizonte",
     "lines": [["NOCTIS", "Bonita balsa. ¿La hiciste tú? Se nota."],
               ["LUZTERNA", "Velo Noctis. Capitana de la Bandera Negra. Roba gatos, roba núcleos, roba protagonismo."],
               ["NOCTIS", "Nos vemos en el siguiente mar, grumete. Si llegas."]]},
    {"id": "b12_gargola", "time": "~1:06", "trigger": "H10", "style": "DIARIO DEL MAR → CÓMIC SILVER AGE", "title": "Tormenta permanente",
     "lines": [["GÁRGOLA", "Rrrrrr… Trescientos años durmiendo en este acantilado. ¿Y tú vienes a hacer ruido?"],
               ["GÁRGOLA", "La tormenta ya no es mía. Llévatela. Hace ruido."],
               ["SISTEMA", "NUEVO ELEMENTO DESCUBIERTO: TORMENTA ⚡ · Tronador se une."]]},
    {"id": "b13_heredero", "time": "~1:15", "trigger": "heroica_1", "style": "COLLAGE GRUNGE", "title": "El Heredero del Trueno",
     "lines": [["LUZTERNA", "Algo truena en el horizonte y no es tu estómago. Un heredero del trueno anda buscando pleito."],
               ["LUZTERNA", "Tienes 25 minutos REALES. No se pausan. Ni con gemas. Ni llorando. Prepárate antes de aceptar."],
               ["RAIJIN", "Ok. Me caes bien. Me voy contigo. Pero yo elijo el camarote."]]},
    {"id": "b14_bandera", "time": "~0:55", "trigger": "bandera_negra", "style": "COLLAGE GRUNGE + PÓSTER RETRO", "title": "Bandera Negra",
     "lines": [["NOCTIS", "Cinco barcos. Veinte minutos. Si ganas, te regalo uno. Si pierdes… me quedo con tu dignidad."],
               ["NOCTIS", "Tch. Quédatelo. Ya me estaba aburriendo de ese barco."]]},
    {"id": "b15_kraken", "time": "~1:44", "trigger": "H13", "style": "NOIR OCEÁNICO + CÓMIC", "title": "El primer escudo",
     "lines": [["SISTEMA", "¡CLANK!"],
               ["LUZTERNA", "¿Una BURBUJA? ¿Desde cuándo los calamares traen escudo? …Ok. Anótalo: NUEVA MECÁNICA: ESCUDOS."],
               ["LUZTERNA", "Te quedas con los planos del escudo. Y con el Bastión, ese acorazado que flota de milagro."]]},
    {"id": "b16_algo_viene", "time": "~1:50 (Reino 24)", "trigger": "algo_viene", "style": "GLITCH → ORQUÍDEA REAL", "title": "Algo viene",
     "lines": [["LUZTERNA", "…Ese barco brilla. Los barcos no brillan. ¿Por qué brilla?"],
               ["SISTEMA", "¡CLANK! (su gato levanta un escudo mágico)"],
               ["LUZTERNA", "¡¿QUÉ PUTAS?! ¡Eso no es un escudo normal!"],
               ["HERALDO", "Interesante. Muy interesante. Nos vemos en las Ruinas, grumete."],
               ["SISTEMA", "Has descubierto un elemento que no debería existir en este mundo: MAGIA ✨"]]},
    {"id": "b17_arcanista", "time": "~2:47", "trigger": "H15", "style": "ORQUÍDEA REAL", "title": "El Ladrón de Páginas",
     "lines": [["ARCANISTA", "Ya conoces mi magia. Ahora conoce mi PACIENCIA. …Mentira, no tengo."],
               ["ARCANISTA", "Llévate a esa gata del grimorio… nunca dejó de corregirme la ortografía."],
               ["LUZTERNA", "¿Y esto? Se cayó de su grimorio. Está frío. Y está… vacío. (FRAGMENTO ??? 1/10)"]]},
    {"id": "b18_archivo", "time": "~3:50 (al limpiar las Ruinas)", "trigger": "H16", "style": "MANGA TINTA → ORQUÍDEA REAL", "title": "Lo que guardan las ruinas",
     "lines": [["LUZTERNA", "Antes de este mar hubo un Archivo. Todo lo que alguien aprendió alguna vez vivía ahí, en forma de gato."],
               ["LUZTERNA", "El Archivo es una pila infinita de cajas. Cada caja es un mundo dibujado con su propio trazo. Los gatos son líquidos: se cuelan de una caja a otra por las gateras. Por eso tu Resonancia 'llama' gatos de otros mundos."],
               ["LUZTERNA", "Cada página se imprimió con una tinta distinta. Por eso cuando un gato ataca, el mundo se reimprime con su estilo. No es un bug: es memoria."],
               ["LUZTERNA", "Distraxia rasgó el Archivo. Las páginas cayeron al mar. Cada gato que juntas es una página que regresa."],
               ["LUZTERNA", "Y yo era la farera. Mi trabajo era que nadie se perdiera. …Ya ves cómo me fue."]]},
    {"id": "b19_estrella", "time": "~3:57", "trigger": "H17", "style": "NEÓN GLITCH", "title": "Cae una estrella",
     "lines": [["ESTRELLA", "Caí una vez del cielo. No me gustó. Ahora tú vas a caer."],
               ["ESTRELLA", "Ahí está… lo que me empujó del cielo. Viene por ti. ¿Lo oyes?"],
               ["SISTEMA", "NUEVO ELEMENTO DESCUBIERTO: CÓSMICO 🌌 · Astra Prima se une."]]},
    {"id": "b20_vacio", "time": "~4:45 (Reino 38)", "trigger": "barco_vacio", "style": "NOIR INVERTIDO", "title": "Un barco que no debería existir",
     "lines": [["SISTEMA", "A VOID SHIP HAS ENTERED YOUR WORLD — 14:59"],
               ["LUZTERNA", "No. No, no, no. Eso no es de este mar. Eso no es de NINGÚN mar."],
               ["LUZTERNA", "No lo vas a hundir. Solo hazle daño. Que se acuerde de ti."]]},
    {"id": "b21_patito", "time": "~4:20 (Reino 36)", "trigger": "revancha_patito", "style": "COZY → ANIME INFERNO", "title": "Hace mucho tiempo, en una balsa…",
     "lines": [["PATITO", "¿Te… te acuerdas de mí? ¡Cuac! …no, por favor, no con ESO."],
               ["LUZTERNA", "Tu primer gato lanzaba bolas de pelo. Hoy borras patos con un dedo. Estoy orgullosa y un poquito asustada."]]},
    {"id": "b22_final", "time": "~5:24", "trigger": "H21", "style": "TODAS (colapso de dimensiones)", "title": "El Primer Mar",
     "lines": [["LUZTERNA", "Este es. El Primer Mar. Todo lo que cae aquí se olvida… a menos que alguien lo recuerde muy fuerte."],
               ["DISTRAXIA", "Este mar recuerda todo lo que el Archivo olvidó. Y yo me encargo de que lo olvide otra vez. Él me lo pidió."],
               ["DISTRAXIA", "Yo no destruyo, grumete. Yo BORRO."],
               ["NOCTIS", "¿Qué? ¿Creíste que te iba a dejar la gloria a ti solito? Muévete, que les tapo la vista. ¡MIL ROSTROS!"],
               ["SISTEMA", "(Fase 3: todos tus gatos tienen la ultimate lista.)"],
               ["LUZTERNA", "¿Ves esa cosa enorme? Ya sabes qué hacer. Mantén… y suelta."]]},
    {"id": "b23_marea_final", "time": "~5:27", "trigger": "boss:6", "style": "EDITORIAL SUIZO (póster)", "title": "Marea Final",
     "lines": [["SISTEMA", "MAREA FINAL — TODA TU ISLA x1000 DURANTE 3:00"],
               ["LUZTERNA", "Mira tu isla. Mírala trabajar. Eso lo hiciste tú. Bueno, ellos. Pero tú les diste de comer."]]},
    {"id": "b24_unknown", "time": "~5:30 (tras la Marea Final)", "trigger": "fin de la Marea Final", "style": "NOIR INVERTIDO", "title": "UNKNOWN ELEMENT DETECTED — NADIE",
     "lines": [["SISTEMA", "(El mar empieza a subir sin viento. Todos tus gatos miran fijamente el mismo punto del cielo. Por primera vez, no es la pared.)"],
               ["SISTEMA", "UNKNOWN ELEMENT DETECTED"],
               ["SISTEMA", "(El cielo se abre como la tapa de una caja. Se asoma una silueta sin cara hecha de estática. El contador de Doblones hace glitch: '???'.)"],
               ["???", "¿Quién derrotó a mi almirante?"],
               ["TUS GATOS", "(todos a la vez) …Nadie."],
               ["???", "(silencio) …Yo soy NADIE."],
               ["NADIE", "NO ONE LIKES CATS."],
               ["SISTEMA", "(Pantalla negra. Se oye un vaso caerse de una mesa en algún lugar.)"],
               ["CAPTION", "NO ONE LIKE CATS. (A NADIE le falta una 'S'. A los gatos no les falta nada.)"],
               ["CAPTION", "CONTINUARÁ →"]]},
    {"id": "b25_creditos", "time": "~5:32", "trigger": "tras CONTINUARÁ", "style": "DIARIO DEL MAR", "title": "Créditos personales",
     "lines": [["PERIÓDICO", "EDICIÓN ESPECIAL: TU CAPÍTULO 1"],
               ["SISTEMA", "Tu primer hábitat era una caja de cartón. Tu último costó {ultimo_habitat}. Tu primer gato lanzaba bolas de pelo. Hoy {mvp} borra medio barco."],
               ["SISTEMA", "Barcos hundidos: {victorias} · Gatos descubiertos: {catdex}/54 · Momento favorito: {momento}"],
               ["NOCTIS", "Me debes una. Y un camarote con vista al mar."],
               ["LUZTERNA", "Capítulo 1 completo. Tu isla seguirá produciendo. Nos vemos en el próximo mar."]]}
]

RESONANCE_COPY = [
    "{A} y {B} se fueron a invocar otro gatito. Regresan en {t}. No toques la puerta.",
    "{A} y {B} se fueron a hacer quién sabe qué…",
    "Tus gatos entraron en Resonancia. A ver qué invocan…",
    "{A} y {B} están 'resonando'. Así le dicen ahora.",
    "Proceso sagrado en curso. Y privado. MUY privado.",
    "{A} y {B} prendieron una vela aromática. Mal presagio para el Catdex de tus enemigos."
]
REVEAL_COPY = {
    "common": ["Salió {name}. Bonito. Normalito. Bonito.", "{name}. Un clásico. Los clásicos hunden barcos."],
    "rare": ["{name}! Raro. Como tú.", "¿{name}? Ese sí no lo esperaba."],
    "epic": ["¡NOOOOO! ¡{name}! ¡ÉPICO!", "¡PUTA MADRE, MIRA LO QUE TE SALIÓ! ({name})"],
    "legendary": ["Un Primordial. {name}. Arrodíllate. (Es broma. O no.)"],
    "mythic": ["…", "{name}. No digas nada. Solo mira."],
    "secret": ["??? → {name}. Esto no estaba en ningún manual.", "¿Cómo putas sacaste eso? — todos tus amigos, mañana."],
    "duplicate": ["Duplicado → +{orbs} Orbes de {name}. ('¡ME FALTABAN {missing}!')"]
}
DEFEAT_COPY = [
    "Perdiste. Pero te llevas chatarra, oro y la dignidad… bueno, chatarra y oro.",
    "Derrota. El mar 1, tú 0. Revancha en 3, 2, 1…",
    "Te hundieron con estilo. Eso cuenta. (Y cuenta para el Análisis del Jefe.)"
]
