# -*- coding: utf-8 -*-
"""Misiones encadenadas por progreso (cero diarias). 4 cadenas: Historia (H), Capitán (C), Criador (K), Explorador (E).
Cada misión enseña algo, abre algo o avanza la historia (purpose: teach/open/story).
Premio 'std' = balance.kingdom.mission_reward (Doblones = 60 s de ingreso, comida = 60 s de producción, 15% de 1 gema,
5 Orbes de Alma) + Ronroneo balance.ronroneo.base_min.mission + XP balance.kingdom.xp_rewards_pct_of_bar.mission + Momentum."""


def M(id, chain, title, goal, trigger, purpose, reward=None, line=None, unlocks=None, est=None):
    return {"id": id, "chain": chain, "title": title, "goal": goal, "trigger": trigger, "purpose": purpose,
            "reward": {"std": True, **(reward or {})}, "unlocks": unlocks or [], "line": line, "estTime": est}


MISSIONS = [
    # ============================================================ HISTORIA
    M("H01", "historia", "¡Despierta, Canelo!", {"type": "tap_cat", "cat": "c_canelo", "text": "Toca a Canelo para despertarlo."},
      "start", "teach", {"std": False, "gold": 10}, "Toca. Con cariño… o no, tú sabrás.", ["K01"], "1:10"),
    M("H02", "historia", "¿Cómo se llama?", {"type": "name_cat", "text": "Ponle nombre a tu primer gato (o acepta 'Canelo')."},
      "mission:H01", "teach", {"std": False, "gold": 20}, "Si le pones 'Michi' no te juzgo. Mucho.", [], "2:00"),
    M("H03", "historia", "Algo huele a pescado", {"type": "harvest_food", "amount": 50, "text": "Junta 50 Pescaditos en el Muelle."},
      "mission:H02", "teach", {"std": False, "gold": 300, "food": 100, "gems": 1}, "Los gatos comen. Mucho.", ["K02"], "3:15"),
    M("H04", "historia", "Ese gato tiene hambre", {"type": "cat_level", "cat": "any", "level": 3, "text": "Alimenta a un gato hasta nivel 3 (¡ÑAM! x8)."},
      "mission:H03", "teach", {"orbsOfFedCat": 5}, "¿Viste? Creció.", [], "4:00"),
    M("H05", "historia", "Ahora haz que valga la pena", {"type": "win_battle", "stage": "1-1", "text": "Lleva a tus gatos a su primer combate y hunde al Patito Pirata."},
      "mission:H04", "teach", {"goldenLoot": True}, "¿Ves ese patito de hule? Es pirata. Y nos ve feo.", ["C01", "H07", "puerto_combate"], "6:00"),
    M("H06", "historia", "Tus gatos se fueron a invocar otro", {"type": "resonance_start", "count": 1, "text": "Lleva a Canelo y Brote al Santuario de Resonancia (resultado garantizado en 90 s)."},
      "mission:C01", "teach", {}, "Es sagrado. Y privado.", ["santuario_resonancia", "K07"], "8:00"),
    M("H07", "historia", "Eso no era una nube", {"type": "reach_kl", "kl": 3, "text": "Llega a Reino 3."},
      "mission:H05", "story", {"gems": 1}, "…Eso no era una nube.", ["E01", "E02", "micro:pez_dorado"], "7:00"),
    M("H08", "historia", "El Capitán Bigotes Rotos", {"type": "defeat_boss", "boss": 1, "text": "Derrota al jefe de la Bahía Sardina."},
      "stage_cleared:1-8", "story", {"boss": 1}, "Tiene barriles de pólvora en la cubierta. Yo nomás digo.", ["H09", "C10", "E11"], "~28:00"),

    M("H09", "historia", "Una máscara en el horizonte", {"type": "win_battle", "zone": 2, "count": 1, "text": "Gana tu primera batalla en los Acantilados de Piedra."},
      "boss:1", "story", {}, "Velo Noctis. Roba gatos, roba núcleos, roba protagonismo.", [], "~31:00"),

    M("H10", "historia", "Tormenta permanente", {"type": "defeat_boss", "boss": 2, "text": "Derrota a La Gárgola Ronroneante."},
      "stage_cleared:2-8", "story", {"boss": 2}, "Trescientos años dormida. Despiértala de un cañonazo.", ["C16"], "~1:06"),

    M("H11", "historia", "El Heredero del Trueno", {"type": "event_complete", "event": "heroica_1", "text": "Completa la Expedición Heroica (o al menos 5 nodos)."},
      "event_presage:heroica_1", "story", {}, "25 minutos REALES. No se pausan. Ni llorando.", [], "~1:15"),

    M("H12", "historia", "Bandera Negra", {"type": "own_ship_or_event", "ship": "merodeador", "event": "bandera_negra", "text": "Gana el evento Bandera Negra (o consigue el Merodeador)."},
      "event_presage:bandera_negra", "story", {}, "Si pierdes, se queda con tu dignidad.", ["C17"], "~0:55"),

    M("H13", "historia", "El primer escudo", {"type": "defeat_boss", "boss": 3, "text": "Derrota al Kraken Voltaico."},
      "stage_cleared:3-8", "story", {"boss": 3}, "¿Desde cuándo los calamares traen escudo?", ["C19", "C20"], "~1:44"),

    M("H14", "historia", "Algo viene", {"type": "win_battle", "battle": "story_heraldo", "text": "Investiga el barco que brilla en el horizonte."},
      "element_unlock_trigger:magic (balance kl:24)", "story", {}, "Los barcos no brillan. ¿Por qué brilla?", ["element:magic"], "~1:50"),

    M("H15", "historia", "El Ladrón de Páginas", {"type": "defeat_boss", "boss": 4, "text": "Derrota al Arcanista."},
      "stage_cleared:4-8", "story", {"boss": 4}, "Nos vemos en las Ruinas, dijo. Pues vamos.", ["C24"], "~2:47"),

    M("H16", "historia", "Lo que guardan las ruinas", {"type": "win_battle", "battle": "secret_orquesta", "text": "Limpia las Ruinas Arcanas y entra al santuario que hay debajo."},
      "expansion:6", "story", {"gems": 2}, "Ahí abajo suena algo. Una nota. Una sola.", [], "~3:50"),

    M("H17", "historia", "Cae una estrella", {"type": "defeat_boss", "boss": 5, "text": "Derrota a la Estrella Errante."},
      "stage_cleared:5-8", "story", {"boss": 5}, "Algo la empujó del cielo. ¿Qué empuja estrellas?", [], "~3:57"),

    M("H18", "historia", "La Grieta", {"type": "event_complete", "event": "heroica_2", "text": "Completa la Expedición Heroica 'Grieta Cósmica'."},
      "event_presage:heroica_2", "story", {}, "¡MATEN A ESE YA!", [], "~4:35"),

    M("H19", "historia", "Un barco que no debería existir", {"type": "damage_pct", "battle": "event_vacio", "pct": 0.15, "text": "Hazle al menos 15% de daño al Barco del Vacío antes de que se vaya."},
      "event:barco_vacio", "story", {"gems": 2}, "No lo vas a hundir. Que se acuerde de ti.", ["E25"], "~4:45"),

    M("H20", "historia", "Hace mucho tiempo, en una balsa…", {"type": "win_battle", "battle": "story_patito_revancha", "text": "Vuelve a la Bahía Sardina. Alguien te espera."},
      "kl:36", "story", {"gems": 1}, "Él sí se acuerda de ti.", [], "~4:20"),

    M("H21", "historia", "El Primer Mar", {"type": "defeat_boss", "boss": 6, "text": "Derrota al Leviatán Almirante."},
      "stage_cleared:6-8", "story", {"boss": 6}, "Todo lo que cae aquí se olvida… a menos que alguien lo recuerde muy fuerte.", ["chapter_end"], "~5:24"),

    M("H22", "historia", "Continuará", {"type": "watch", "text": "Mira lo que pasó después."},
      "boss:6", "story", {"std": False, "gems": 3}, "Nos vemos en el próximo mar.", ["post:mar_abierto", "post:marea_nueva", "cat:s_noctis"], "~6:15"),

    # ============================================================ CAPITÁN

    M("C01", "capitan", "Al agua, patos", {"type": "win_battle", "count": 2, "text": "Gana 2 batallas más en la Bahía Sardina."},
      "mission:H05", "teach", {}, "Arrastra desde el gato y suelta. Fácil. Como robarle a un pato.", ["H06"], "7:30"),
    M("C02", "capitan", "Un cañón que sí pegue", {"type": "ship_upgrade", "family": "weapon", "mk": 2, "text": "Mejora las Armas a Mk II en el Astillero."},
      "mission:C01", "teach", {}, "Chatarra + Doblones = cañón que no da pena.", ["C03"], "~10:00"),
    M("C03", "capitan", "Casco que no se moje", {"type": "ship_upgrade", "family": "hull", "mk": 2, "text": "Mejora el Casco a Mk II (Balandra)."},
      "mission:C02", "teach", {}, "Un barco que no se hunde es un barco que gana. Más o menos.", ["C04"], "~14:00"),
    M("C04", "capitan", "Bombea ese tiro", {"type": "destroy_module_arc", "text": "Destruye un módulo que esté detrás de un muro (tiro bombeado)."},
      "stage_reached:1-3", "teach", {}, "Si hay muro, tíralo por arriba.", [], "~7:00"),
    M("C05", "capitan", "Gorrión", {"type": "own_ship", "ship": "gorrion", "text": "Compra el Gorrión en el Astillero."},
      "kl:5", "open", {}, "Un barco con motor. MOTOR. Qué lujo.", ["C06"], "~9:00"),
    M("C06", "capitan", "Tripulación completa", {"type": "crew_full", "ship": "gorrion", "text": "Asigna 4 gatos al Gorrión."},
      "mission:C05", "teach", {}, "Cada camarote es una decisión. ¿Quién va arriba, quién va atrás?", [], "~10:00"),
    M("C07", "capitan", "Hunde, no rompas", {"type": "win_by", "condition": "sink", "text": "Gana una batalla hundiendo al enemigo (inundación)."},
      "mission:C06", "teach", {}, "Un hoyito abajo vale más que diez arriba.", ["module:pump", "module:bulkhead"], "~18:00"),
    M("C08", "capitan", "Lee el barco", {"type": "destroy_module", "module": "powder", "text": "Haz explotar una santabárbara enemiga."},
      "stage_reached:1-4", "teach", {}, "¿Ves ese barril? Sí. ESE.", [], "~16:00"),
    M("C09", "capitan", "Bahía limpia", {"type": "stages_cleared", "zone": 1, "count": 8, "text": "Gana las 8 etapas de la Bahía Sardina."},
      "mission:C04", "open", {}, "Ya nomás falta el jefe.", ["H08"], "~30:00"),
    M("C10", "capitan", "Mk III", {"type": "ship_upgrade", "family": "any", "mk": 3, "text": "Lleva cualquier familia a Mk III (Fragata)."},
      "boss:1", "teach", {}, "Cada jefe que tumbas sube el tope de Mk. Regla: jefes + 2.", [], "~40:00"),
    M("C11", "capitan", "Tu primera ultimate", {"type": "use_ultimate", "count": 1, "text": "Llena el medidor de un gato y usa su ultimate (F)."},
      "first_meter_full", "teach", {}, "Pantalla negra, viñetas, grito. Ya sabes cómo va.", ["module:arcane"], "~20:00"),
    M("C12", "capitan", "Astillero creativo", {"type": "edit_layout", "text": "Mueve un módulo o camarote en el editor y prueba contra el muñeco."},
      "mission:C11", "teach", {}, "Desmontar es gratis. Experimenta.", [], "~25:00"),
    M("C13", "capitan", "Victoria perfecta", {"type": "win_perfect", "count": 1, "text": "Gana sin perder ningún gato."},
      "mission:C09", "teach", {}, "Nadie se mojó. Bueno, todos se mojaron. Pero nadie se murió.", [], "~35:00"),
    M("C14", "capitan", "Asalto rápido", {"type": "quick_assault", "count": 1, "text": "Usa Asalto Rápido en una etapa que ya ganaste."},
      "can_quick_assault", "teach", {}, "Ya les ganaste. No hace falta humillarlos otra vez. (Bueno, sí, pero en 5 segundos.)", [], "~45:00"),
    M("C15", "capitan", "Aguas Estrechas", {"type": "errand", "errand": "enc_aguas_estrechas", "text": "Completa el Encargo 'Aguas Estrechas' (solo barcos chicos)."},
      "stage_cleared:2-3", "teach", {}, "No todos los barcos caben en todos lados. Como tus ex.", [], "~50:00"),
    M("C16", "capitan", "Dos armas, dos ideas", {"type": "equip_weapon_types", "distinct": 2, "text": "Equipa 2 tipos de arma distintos (p. ej. Cañón + Bobina Tesla)."},
      "boss:2", "teach", {}, "Una Bobina Tesla con un gato eléctrico a bordo… ya verás.", [], "~1:15"),
    M("C17", "capitan", "Merodeador", {"type": "own_ship", "ship": "merodeador", "text": "Consigue el Merodeador (evento o astillero)."},
      "kl:15", "open", {}, "Bandera negra, cero modales.", ["artifact:kit_reparacion", "artifact:bomba_humo"], "~0:50"),

    M("C18", "capitan", "Saqueo", {"type": "destroy_modules_with", "ship": "merodeador", "count": 30, "text": "Destruye 30 módulos con el Merodeador."},
      "mission:C17", "teach", {}, "Cada módulo que rompes suelta cofrecitos. Rompe más.", [], "~1:30"),
    M("C19", "capitan", "Escudo arriba", {"type": "equip_shield", "text": "Instala tu primer escudo."},
      "boss:3", "teach", {}, "Ahora tú también dices 'CLANK'.", ["artifact:burbuja_emergencia"], "~1:45"),
    M("C20", "capitan", "El acorazado", {"type": "own_ship", "ship": "bastion", "text": "Compra el Bastión."},
      "boss:3", "open", {}, "Siete camarotes. Siete. ¿Tienes siete gatos decentes?", ["artifact:ancla_emergencia"], "~2:27"),

    M("C21", "capitan", "Flota", {"type": "own_ships", "count": 3, "text": "Ten 3 barcos."},
      "mission:C20", "teach", {}, "Un barco para cada pleito.", [], "~2:24"),
    M("C22", "capitan", "Rescate Gatuno", {"type": "errand", "errand": "enc_rescate", "text": "Completa el Encargo 'Rescate Gatuno' (solo 3 gatos)."},
      "stage_cleared:2-6", "teach", {}, "Tres gatos. Ni uno más. Elige bien.", [], "~1:05"),
    M("C23", "capitan", "Asedio Pesado", {"type": "errand", "errand": "enc_asedio_pesado", "text": "Completa el Encargo 'Asedio Pesado'."},
      "stage_cleared:4-6", "teach", {}, "Armadura doble. Necesitas el barco gordo.", [], "~2:50"),
    M("C24", "capitan", "Bajel Arcano", {"type": "own_ship", "ship": "bajel", "text": "Compra el Bajel Arcano."},
      "boss:4", "open", {}, "Un barco que mueve gatos de cuarto. Tu mamá nunca te dejó hacer eso.", ["artifact:catnip"], "~4:31"),

    M("C25", "capitan", "Tormenta Arcana", {"type": "errand", "errand": "enc_tormenta_arcana", "text": "Completa el Encargo 'Tormenta Arcana' (solo escudos arcanos)."},
      "stage_cleared:5-3", "teach", {}, "Aquí los escudos normales no sirven. ¿Adivina cuál barco sí?", [], "~4:00"),
    M("C26", "capitan", "Mk VII", {"type": "ship_upgrade", "family": "any", "mk": 7, "text": "Lleva cualquier familia a Mk VII (Casco Celestial)."},
      "boss:5", "teach", {}, "¿Ves esas constelaciones en el casco? Se mueven. No sé por qué.", [], "~5:10"),

    M("C27", "capitan", "Simulacro", {"type": "use_automation", "automation": "auto_battle", "text": "Activa el Simulacro (auto-batalla en etapas ganadas)."},
      "kl:40", "teach", {}, "Tu flota ya sabe pelear sola. Tú ocúpate de lo importante.", [], "~4:34"),

    M("C28", "capitan", "Rango Oro", {"type": "cat_rank", "rank": "oro_1", "text": "Lleva a un gato al rango Oro I (170 KO entre módulos y gatos)."},
      "mission:C13", "teach", {}, "Cada módulo roto cuenta. Aunque pierdas.", [], "~3:00"),

    # ============================================================ CRIADOR
    M("K01", "criador", "Recoge tu oro", {"type": "collect_gold", "times": 3, "text": "Recolecta los Doblones de un hábitat 3 veces."},
      "mission:H01", "teach", {}, "Los gatos producen nomás por existir.", [], "2:00"),
    M("K02", "criador", "Pesca de verdad", {"type": "harvest", "crop": "sardinas", "count": 3, "text": "Cosecha Sardinas 3 veces."},
      "mission:H03", "teach", {}, "Planta, espera (o no), cosecha.", [], "5:00"),
    M("K03", "criador", "Una casa para Brote", {"type": "build_habitat", "element": "nature", "text": "Construye un hábitat de Naturaleza: Brote no tiene casa y no produce."},
      "mission:K01", "teach", {}, "Un gato sin casa no produce. Y se queja.", [], "3:45"),
    M("K04", "criador", "Crecidito", {"type": "cat_level", "cat": "any", "level": 5, "text": "Sube a un gato a nivel 5."},
      "mission:H04", "teach", {}, "¡ÑAM! ¡ÑOM! ¡GULP!", [], "9:00"),
    M("K05", "criador", "Cesta de Mimbre", {"type": "upgrade_habitat", "tier": 2, "text": "Mejora un hábitat a Cesta de Mimbre."},
      "kl:4", "teach", {}, "De caja de cartón a canasta. Así empiezan los imperios.", [], "~12:00"),
    M("K06", "criador", "Anchoas Saltarinas", {"type": "harvest", "crop": "anchoas", "count": 1, "text": "Siembra y cosecha Anchoas."},
      "kl:4", "teach", {}, "Más tiempo, más comida. Elige según cuánto te vas a quedar.", ["module:pantry"], "~13:00"),
    M("K07", "criador", "¿Qué salió?", {"type": "resonance_hatch", "count": 1, "text": "Revela tu primera Resonancia."},
      "mission:H06", "teach", {"gems": 1}, "¡Un Raro a la primera!", ["K08", "catdex"], "9:30"),
    M("K08", "criador", "Registra a tus gatos", {"type": "species_owned", "count": 5, "text": "Registra 5 especies en el Catdex."},
      "mission:K07", "teach", {}, "73/450 es adictivo. Aquí son 54. Peor.", [], "~18:00"),
    M("K09", "criador", "Alimentar hasta…", {"type": "use_feature", "feature": "feed_bulk", "text": "Usa 'Alimentar hasta nivel X'."},
      "kl:6", "teach", {}, "Mira los números rodar. Qué rico.", [], "~20:00"),
    M("K10", "criador", "Granja en piloto automático", {"type": "use_feature", "feature": "crop_repeat", "text": "Activa 'Repetir receta' en una granja."},
      "kl:9", "teach", {}, "Ya aprendiste a sembrar. Ahora deja de hacerlo tú.", [], "~26:00"),
    M("K11", "criador", "Torre Rascadora", {"type": "upgrade_habitat", "tier": 3, "text": "Mejora un hábitat a Torre Rascadora."},
      "kl:9", "teach", {}, "Los gatos aman las torres. Y la renta.", [], "~28:00"),
    M("K12", "criador", "Primeros orbes", {"type": "orbs_of_species", "amount": 10, "text": "Junta 10 Orbes de Alma de un mismo gato."},
      "first_orb_drop", "open", {}, "Un duplicado nunca es inútil.", ["altar_almas"], "~20:00"),
    M("K13", "criador", "Una estrella más", {"type": "star_up", "stars": 2, "text": "Sube un gato a ★2 en el Altar de Almas."},
      "mission:K12", "teach", {}, "¡TUNK! Sello de goma. Más fuerte.", [], "~35:00"),
    M("K14", "criador", "El Primordial", {"type": "own_rarity", "rarity": "legendary", "text": "Consigue un Primordial (Legendario)."},
      "boss:1", "story", {}, "Los Primordiales son los padres de cada elemento.", [], "~33:00"),
    M("K15", "criador", "Set completo", {"type": "catdex_set", "count": 1, "text": "Completa cualquier set del Catdex (p. ej. Piedra Viva)."},
      "mission:K08", "open", {}, "Un set completo cambia una regla. No un porcentaje: una REGLA.", [], "~45:00"),
    M("K16", "criador", "Dos a la vez", {"type": "resonance_parallel", "count": 2, "text": "Ten 2 Resonancias activas al mismo tiempo."},
      "expansion:3", "teach", {}, "Dos parejas, dos misterios.", [], "~35:00"),
    M("K17", "criador", "¡Épico!", {"type": "own_rarity", "rarity": "epic", "text": "Consigue un gato Épico (padres Nv15+)."},
      "kl:10", "teach", {}, "¡NOOOOO! (de felicidad)", [], "~1:00"),
    M("K18", "criador", "Casita de Coral", {"type": "upgrade_habitat", "tier": 4, "text": "Mejora un hábitat a Casita de Coral."},
      "kl:15", "teach", {}, "Coral. En tierra. No preguntes.", [], "~1:00"),
    M("K19", "criador", "Salmón Imperial", {"type": "harvest", "crop": "salmon", "count": 1, "text": "Cosecha Salmón Imperial."},
      "kl:15", "teach", {}, "Antes las sardinas eran un lujo. Míranos.", [], "~1:05"),
    M("K20", "criador", "Cola de Resonancia", {"type": "use_feature", "feature": "resonance_queue", "text": "Deja 3 parejas en la Cola de Resonancia."},
      "kl:18", "teach", {}, "Que se encolen solitos.", [], "~1:20"),
    M("K21", "criador", "Mar de Pescados Automático", {"type": "use_feature", "feature": "auto_harvest", "text": "Activa la Auto-cosecha al Silo."},
      "kl:21", "teach", {}, "Tu mar de pescados ya trabaja solo.", [], "~1:25"),
    M("K22", "criador", "Mutante", {"type": "own_mutation", "count": 1, "text": "Consigue un gato con mutación."},
      "kl:20", "teach", {}, "MUTACIÓN: Conductividad. AHHHHH.", [], "~1:30"),
    M("K23", "criador", "Palacio de Cojines", {"type": "upgrade_habitat", "tier": 5, "text": "Mejora un hábitat a Palacio de Cojines (necesita cristales)."},
      "kl:21", "teach", {}, "Los cristales salen de pelear. Así funciona este mar.", [], "~1:40"),
    M("K24", "criador", "Gatos con oficio", {"type": "assign_worker", "count": 1, "text": "Asigna un gato como trabajador (Banquero, Granjero, Constructor o Viajero)."},
      "kl:24", "teach", {}, "Si trabaja en la isla, no sube al barco. Decide.", [], "~1:45"),
    M("K25", "criador", "Efecto secundario", {"type": "star_up", "stars": 3, "text": "Sube un gato a ★3 (desbloquea su efecto secundario)."},
      "mission:K13", "teach", {}, "Ahora su ataque hace una cosa más. Una cosa MÁS.", [], "~2:00"),
    M("K26", "criador", "Templo del Ronroneo", {"type": "upgrade_habitat", "tier": 6, "text": "Mejora un hábitat a Templo del Ronroneo."},
      "kl:27", "teach", {}, "Un templo. Para gatos. Lo lógico.", [], "~2:40"),
    M("K27", "criador", "Treinta", {"type": "species_owned", "count": 30, "text": "Registra 30 especies."},
      "mission:K15", "story", {}, "Más de la mitad. Ya hueles a coleccionista.", [], "~3:00"),

    M("K28", "criador", "Herencia", {"type": "inherit_trait", "count": 1, "text": "Haz una Resonancia donde el hijo herede el rasgo de un padre."},
      "kl:30", "teach", {}, "Sacó lo impaciente del papá.", [], "~3:20"),
    M("K29", "criador", "Banquete del Leviatán", {"type": "plant", "crop": "leviatan", "text": "Siembra un Banquete del Leviatán (cultivo largo para cuando te vayas)."},
      "kl:33", "teach", {}, "Seis horas. Para la noche. O para que lo aceleres jugando, como siempre.", [], "~4:10"),
    M("K30", "criador", "Santuario Arcano", {"type": "upgrade_habitat", "tier": 7, "text": "Mejora un hábitat a Santuario Arcano."},
      "kl:31", "teach", {}, "Antes 700 Doblones eran una fortuna. ¿Te acuerdas?", [], "~4:25"),

    M("K31", "criador", "Cuarenta", {"type": "species_owned", "count": 40, "text": "Registra 40 especies."},
      "mission:K27", "story", {}, "Alguien quiere tomarle foto a tu colección…", ["route:s_lumen"], "~4:40"),

    M("K32", "criador", "Nivel Leyenda", {"type": "cat_level", "cat": "any", "level": 40, "text": "Sube un gato a nivel 40 (umbral Leyenda: su ataque puede volverse mítico)."},
      "kl:35", "teach", {}, "10% de meteorito. O de tsunami. O de árbol. Depende del gato.", [], "~5:15"),

    # ============================================================ EXPLORADOR
    M("E01", "explorador", "Recolectar todo", {"type": "use_feature", "feature": "collect_all", "text": "Usa 'Recolectar todo'."},
      "kl:3", "teach", {}, "Ya aprendiste. Toma: un botón.", [], "7:00"),
    M("E02", "explorador", "Bosque Costero", {"type": "buy_expansion", "n": 1, "text": "Compra la expansión Bosque Costero."},
      "kl:3", "open", {}, "Más isla, más gatos, más problemas.", ["E03", "K15"], "~7:00"),
    M("E03", "explorador", "Debajo de las rocas", {"type": "clear_expansion", "n": 1, "text": "Termina de limpiar el Bosque Costero."},
      "mission:E02", "open", {}, "¿Eso es un santuario? Está sellado.", ["E05"], "~7:30"),
    M("E04", "explorador", "¡Pez dorado!", {"type": "micro_complete", "count": 1, "text": "Completa tu primer microevento."},
      "first_micro", "teach", {}, "Reloj rojo chiquito. Esos no esperan.", [], "14:00"),
    M("E05", "explorador", "El santuario sellado", {"type": "win_battle", "battle": "duel_guardian_bosque", "text": "Abre el santuario del bosque (Reino 5) y vence a su guardián."},
      "kl:5 & mission:E03", "open", {"gems": 2}, "Un guardián musgoso. Y de mal humor.", [], "~20:00"),
    M("E06", "explorador", "Acantilado Rocoso", {"type": "buy_expansion", "n": 2, "text": "Compra el Acantilado Rocoso."},
      "kl:7", "open", {}, "Ruinas, rocas y un segundo constructor.", ["E07"], "~12:00"),
    M("E07", "explorador", "Fósil en la pared", {"type": "expansion_secret", "n": 2, "text": "Saca el fósil incrustado en el acantilado."},
      "mission:E06", "open", {"gems": 2}, "Clic, clic, clic… ¡crack!", [], "~13:00"),
    M("E08", "explorador", "Reloj rojo", {"type": "event_complete", "event": "flash", "count": 1, "text": "Completa tu primer Evento Flash."},
      "first_flash_presage", "teach", {}, "Verde: no hay prisa. Rojo: AHORA.", [], "~9:00"),
    M("E09", "explorador", "Isla Volcánica", {"type": "buy_expansion", "n": 3, "text": "Compra la Isla Volcánica."},
      "kl:12", "open", {}, "600 mil era imposible… ¿te acuerdas? (Bueno, aquí son 120K, pero el chiste es el mismo.)", ["E10", "K16"], "~34:00"),
    M("E10", "explorador", "La Forja Dormida", {"type": "expansion_secret", "n": 3, "text": "Enciende la forja apagada con un gato 🔥 de nivel 10+."},
      "mission:E09", "open", {"gems": 2}, "Algo se está calentando. Literal.", ["weapon:mortero"], "~36:00"),
    M("E11", "explorador", "Cat's Gambit", {"type": "gambit_play", "count": 1, "text": "Juega una mano en la Mesa del Gato (se puede ocultar en Ajustes; si está oculta, se completa sola)."},
      "boss:1", "teach", {}, "¿Se cae el vaso o no se cae? Probabilidades a la vista. Sin trampas.", [], "~40:00"),
    M("E12", "explorador", "¡Sinergia descubierta!", {"type": "reaction_discovered", "count": 1, "text": "Provoca tu primera reacción elemental (p. ej. Vapor o Conducción)."},
      "mission:K07", "teach", {}, "Agua + rayo. Tu abuela te lo advirtió.", ["grimorio", "artifact:bengala"], "~25:00"),
    M("E13", "explorador", "Puerto de las Mareas", {"type": "buy_expansion", "n": 4, "text": "Compra el Puerto de las Mareas."},
      "kl:17", "open", {}, "Desde aquí salen las expediciones. Y entra la niebla.", ["E14", "E15"], "~1:15"),

    M("E14", "explorador", "Mándalos a pasear", {"type": "expedition_complete", "count": 1, "text": "Completa tu primera Expedición."},
      "mission:E13", "teach", {}, "Regresan con chatarra, cristales y anécdotas.", [], "~1:30"),

    M("E15", "explorador", "Botella del Faro", {"type": "expansion_secret", "n": 4, "text": "Abre la botella que llegó al Puerto."},
      "mission:E13", "story", {"gems": 2}, "La carta está firmada con un antifaz.", [], "~1:20"),
    M("E16", "explorador", "Glaciar Bigote", {"type": "buy_expansion", "n": 5, "text": "Compra el Glaciar Bigote."},
      "kl:22", "open", {}, "Frío, focas y un gato congelado con un cañón raro.", ["E17"], "~1:55"),

    M("E17", "explorador", "Gato en el hielo", {"type": "expansion_secret", "n": 5, "text": "Descongela al gato del glaciar con un gato 🔥."},
      "mission:E16", "open", {"gems": 2}, "Se llevó el cañón al hielo. ¿Por qué? Nadie sabe.", ["weapon:escarcha"], "~2:05"),
    M("E18", "explorador", "Rumores", {"type": "secret_rumors", "count": 3, "text": "Encuentra pistas de 3 gatos '???' secretos."},
      "mission:E15", "open", {"gems": 1}, "Hay gatos que no salen en ningún manual.", [], "~2:30"),
    M("E19", "explorador", "Ruinas Arcanas", {"type": "buy_expansion", "n": 6, "text": "Compra las Ruinas Arcanas."},
      "kl:27", "open", {}, "Columnas, libros flotando y una nota que suena sola.", ["H16"], "~3:45"),

    M("E20", "explorador", "Arrecife Prismático", {"type": "buy_expansion", "n": 7, "text": "Compra el Arrecife Prismático."},
      "kl:31", "open", {}, "Corales que brillan y una mina de Orbes Prisma.", ["E21"], "~4:30"),

    M("E21", "explorador", "Concha Espejo", {"type": "expansion_secret", "n": 7, "text": "Asómate a la concha gigante del arrecife."},
      "mission:E20", "open", {"gems": 2}, "Te ves bien. Tu barco también.", ["shield:espejo"], "~4:33"),

    M("E22", "explorador", "Atolón Estelar", {"type": "buy_expansion", "n": 8, "text": "Compra el Atolón Estelar."},
      "kl:36", "open", {}, "Los gatos pescan organismos espaciales. Normal.", ["E23"], "~5:05"),

    M("E23", "explorador", "Faro del Primer Mar", {"type": "expansion_secret", "n": 8, "text": "Enciende el faro del atolón."},
      "mission:E22", "story", {"gems": 4}, "Apunta a la Zona 6. Ahí está.", [], "~5:08"),

    M("E24", "explorador", "Grimorio de Sinergias", {"type": "reaction_discovered", "count": 8, "text": "Descubre 8 reacciones elementales."},
      "mission:E12", "teach", {"gems": 2}, "Ya no juegas: haces química.", [], "~4:30"),
    M("E25", "explorador", "Fragmentos", {"type": "void_fragments", "count": 7, "text": "Junta 7/10 Fragmentos del Vacío."},
      "mission:H19", "story", {}, "ELEMENT: ??? 7/10. Ay, no.", [], "~5:30"),
    M("E26", "explorador", "Viaje largo", {"type": "expedition_complete", "duration_s": 14400, "count": 1, "text": "Completa una Expedición de 4 h (déjala cuando te vayas)."},
      "mission:E14", "teach", {}, "Para cuando te vayas a dormir. El mundo sigue.", [], "offline"),
]
